/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2018-04-20 02:06:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.adminMy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.security.auth.callback.ConfirmationCallback;
import member.model.vo.*;
import review.model.vo.*;
import java.util.*;
import reply.model.vo.*;
import java.text.*;
import total.model.vo.*;

public final class admin_005fmy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("reply.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_packages.add("review.model.vo");
    _jspx_imports_packages.add("total.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.security.auth.callback.ConfirmationCallback");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


ArrayList<Total> tlist = new ArrayList<Total>();
if (request.getAttribute("tlist") != null) {
	tlist = (ArrayList<Total>) request.getAttribute("tlist");
}

int count =1;


String business_email[] = null; 
	 if(request.getAttribute("business_email")!=null)
		{
		 business_email= (String[])request.getAttribute("business_email");
		}
 
	//로그인 정보 가져오기
	Manager loginMember=null;
	
	if(session.getAttribute("loginMember")!=null)
	{
		loginMember = (Manager)session.getAttribute("loginMember");

	}
	else 
	{ //로그인 아니라면 index로 강제 소환
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tlocation.href =\"/food/index.jsp\";\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t");
 }
	
//tab 정보 가져오기
	if (request.getAttribute("tab") != null) {
	

      out.write("\r\n");
      out.write("<script> \r\n");
      out.write("var tab = '");
      out.print(request.getAttribute("tab"));
      out.write("';\r\n");
      out.write("console.log(tab);\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar tab = \"tab-1\";\r\n");
      out.write("\tconsole.log(tab);\r\n");
      out.write("</script>\r\n");

	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>푸딩 관리자</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/top-menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/foot.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/left-menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/left-menu-tab.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/right-menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/modInfo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/review.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/replay.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("canvas {\r\n");
      out.write("\t-moz-user-select: none;\r\n");
      out.write("\t-webkit-user-select: none;\r\n");
      out.write("\t-ms-user-select: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script rc=\"/food/resources/js/analytics.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/Chart.bundle.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@\r\n");
      out.write("-webkit-keyframes chartjs-render-animation {\r\n");
      out.write("\tfrom {opacity: 0.99\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\topacity: 1\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("@\r\n");
      out.write("keyframes chartjs-render-animation {\r\n");
      out.write("\tfrom {opacity: 0.99\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\topacity: 1\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".chartjs-render-monitor {\r\n");
      out.write("\t-webkit-animation: chartjs-render-animation 0.001s;\r\n");
      out.write("\tanimation: chartjs-render-animation 0.001s;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"/food/resources/js/utils.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/food/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/jquery.scrollzer.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/skel.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/util.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/main.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/food/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var startPage =1;\r\n");
      out.write("var endPage = 1;\r\n");
      out.write("var maxPage = 1;\r\n");
      out.write("var currentPage = 1;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function deltImg(num)\r\n");
      out.write("{\t\r\n");
      out.write("\r\n");
      out.write("\t$('#imgSpan'+num).html(\"\");\r\n");
      out.write("\timgCount--;\r\n");
      out.write("}\r\n");
      out.write("var imgNum = 2;\r\n");
      out.write("var imgCount = 0;\r\n");
      out.write("function addImage()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tvar newCode = '<span id=\"imgSpan'+imgNum+'\" ><input type=\"hidden\" name=\"oriImg\" value=\"\"><br><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<input type=\"file\" accept=\"image/*\" onchange=\"imgChange('+imgNum+');\" name=\"imgFile'+imgNum+'\" >&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<input type=\"button\" onclick=\"deltImg('+imgNum+');\" value=\"삭제하기\" >&nbsp;<input type=\"hidden\" name=\"fileTagName\" value=\"imgFile'+imgNum+'\" ><br><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<img id=\"img'+imgNum+'\" style=\"width:400px; height:250px;\" alt=\"이미지를 등록하세요\" src=\"\"></span>';\r\n");
      out.write("\t\r\n");
      out.write("\t$('#addImageDiv').append(newCode);\r\n");
      out.write("\timgNum++;\r\n");
      out.write("\timgCount++;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function imgChange(num)\r\n");
      out.write("{\r\n");
      out.write("\tvar preview = document.querySelector('#img'+num);\r\n");
      out.write("\tvar file = document.querySelector('[name=imgFile'+num+']').files[0];\r\n");
      out.write("\tvar reader  = new FileReader(); \r\n");
      out.write("    reader.onloadend = function () { \r\n");
      out.write("           preview.src = reader.result; \r\n");
      out.write("    } \r\n");
      out.write("    if (file) { \r\n");
      out.write("           reader.readAsDataURL(file); \r\n");
      out.write("       } else { \r\n");
      out.write("           preview.src = \"\"; \r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("\t\r\n");
      out.write("\treviewPaging(1);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('[name=delCheck]').change(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(this).is(\":checked\")==true)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#'+$(this).attr('id')+'email').prop(\"checked\",true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\telse if($(this).is(\":checked\")==false)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#'+$(this).attr('id')+'email').prop(\"checked\",false);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#delCheck').change(function(){\r\n");
      out.write("\t\t\t//사업자 미승인 회원 전체 체크박스 선택\r\n");
      out.write("\t\tif(\t$('#delCheck').is(\":checked\")==true )\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('[name=delCheck]').each(function(){\r\n");
      out.write("\t\t\t\t$(this).prop(\"checked\",true);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('[name=business_email]').each(function(){\r\n");
      out.write("\t\t\t\t$(this).prop(\"checked\",true);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\telse if ( $('#delCheck').is(\":checked\")==false )\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('[name=delCheck]').each(function(){\r\n");
      out.write("\t\t\t\t$(this).prop(\"checked\",false);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('[name=business_email]').each(function(){\r\n");
      out.write("\t\t\t\t$(this).prop(\"checked\",false);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

	if(business_email !=null){
	for(int i=0;i<business_email.length;i++){
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\ttype : \"post\",\r\n");
      out.write("\turl : \"/food/bapprovsendemail\",\r\n");
      out.write("\tdata:{\"business_email\" : '");
      out.print(business_email[i]);
      out.write("'\r\n");
      out.write("\t},\r\n");
      out.write("\tsuccess: function(data){\r\n");
      out.write("\t\tconsole.log('email발송 되닝');\t\t\t\t\r\n");
      out.write("\t\t}\t\t\t\t\r\n");
      out.write("\t});\r\n");
}
      out.write("alert('");
      out.print(request.getAttribute("mailMessage"));
      out.write("');\r\n");
      out.write("\r\n");
}
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif (tab != null) {\r\n");
      out.write("\t\t$('.tab-content').removeClass('current');\r\n");
      out.write("\t\t$('.tabs li').removeClass('current');\r\n");
      out.write("\t\t$('.tabs li a').removeClass('active');\r\n");
      out.write("\t\t$('#' + tab).addClass(' current');\r\n");
      out.write("\t\t$('[data-tab='+tab+'] a').addClass('active');\r\n");
      out.write("\t\tconsole.log('[data-tab='+tab+']');\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$('.tabs li').click(function() {\r\n");
      out.write("\t\tvar tab_cl = $(this).attr('data-tab');\r\n");
      out.write("\r\n");
      out.write("\t\t$('.tabs li').removeClass('current');\r\n");
      out.write("\t\t$('.tab-content').removeClass('current');\r\n");
      out.write("\t\t$(this).addClass('current');\r\n");
      out.write("\t\t$(\".\" + tab_cl).addClass('current');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function againApprovalbutton(bsid,addr){\r\n");
      out.write("\t\r\n");
      out.write("\tvar con = confirm (\"선택한 회원님을 재승인하시겠습니까?\");\r\n");
      out.write("\t\r\n");
      out.write("\tif(con==true){\r\n");
      out.write("\t\tlocation.href =\"/food/approvbtn?bsid=\"+bsid+\"&addr=\"+addr;\t\r\n");
      out.write("\t\talert(\"승인완료!\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function rejectbutton(bsid){\r\n");
      out.write(" \r\n");
      out.write("// 여기까지 하다감\r\n");
      out.write("   //#\r\n");
      out.write("var doublebtn1 ='<input type =\"text\" name = \"rejectReason\" id=\"rejectReason\" placeholder=\"거절 사유를 입력하세요\" style=\"padding-left:0px; font-color:red\">';\r\n");
      out.write("var doublebtn2 ='<input type=\"button\" onclick =\"rejectOKbutton(\\''+bsid+'\\')\" hidden=\"hidden\" value=\"확인\" class=\"btn btn-outline-primary\">&nbsp;'; \r\n");
      out.write("var doublebtn3 ='<input type=\"button\" onclick =\"rejectCancelbutton(\\''+bsid+'\\');\"  value=\"취소\" class=\"btn btn-outline-primary\">'; \r\n");
      out.write("\r\n");
      out.write("$(\"#rejectbutton\" + bsid).html(doublebtn1+doublebtn2+doublebtn3);\r\n");
      out.write("//$('#approvalbutton'+bsid).html();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function rejectOKbutton(bsid){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif($('#rejectReason').val()==\"\"){\r\n");
      out.write("\t\talert(\"거절사유를 입력해주세요!\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"사업자 승인 거절 완료!\");\r\n");
      out.write("\t\t location.href = \"/food/rejectbtn?bsid=\"+bsid+\"&rejectReason=\"+$('#rejectReason').val();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function rejectCancelbutton(bsid){\t\r\n");
      out.write("\tvar btn4= '<input type=\"button\" onclick = \"approvalbutton(\\'' +bsid+'\\',\\'bapprov\\');\" class=\"btn btn-outline-primary\" value=\"승인\">&nbsp;' ;\r\n");
      out.write("\tvar btn5= '<input type=\"button\" onclick = \"rejectbutton(\\''+bsid+'\\');\" class=\"btn btn-outline-primary\" value=\"거절\">' ;\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#rejectbutton\" + bsid).html(btn5);\r\n");
      out.write("\t$('#approvalbutton'+bsid).html(btn4);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function deletebutton(bsid){\r\n");
      out.write("\t var con = confirm(\"정말 삭제하시겠습니까?                                                        삭제된 회원은 탈퇴처리됩니다.\");\r\n");
      out.write("\t\r\n");
      out.write("\t if(con==true){\r\n");
      out.write("\t\t location.href = \"/food/deletebtn?bsid=\"+bsid;\r\n");
      out.write("\t }else{\r\n");
      out.write("\t\t\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("}\r\n");
      out.write("function compulWithDrawButton(bsid){\r\n");
      out.write("\t var con2 =confirm(\"정말 강제 탈퇴 시키겠습니까?\");\r\n");
      out.write("\t if(con2==true){\r\n");
      out.write("\t\t location.href = \"/food/comwithbtn?bsid=\"+bsid;\r\n");
      out.write("\t }else{\r\n");
      out.write("\t\t\r\n");
      out.write("\t }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function withdraw(customerId, pageNum)\r\n");
      out.write("{\r\n");
      out.write("\t var con3 =confirm(\"정말 강제 탈퇴 시키겠습니까?\");\r\n");
      out.write("\t if(con3==true){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t\t \turl : \"/food/cWithdraw\",\r\n");
      out.write("\t\t \tdata : {page : pageNum,\r\n");
      out.write("\t\t \t\tcId : customerId},\r\n");
      out.write("\t\t \ttype : \"get\",\r\n");
      out.write("\t\t \tdataType: \"json\",\r\n");
      out.write("\t\t \t  success: function(data){\r\n");
      out.write("\t\t console.log(\"dd\");\r\n");
      out.write("\t\t \tstartPage =data.startPage;\r\n");
      out.write("\t\t \t\tendPage =data.endPage;\r\n");
      out.write("\t\t \t\tmaxPage = data.maxPage;\r\n");
      out.write("\t\t \t\tcurrentPage = data.currentPage;\r\n");
      out.write("\t\t \t\t\r\n");
      out.write("\t\t \t\t  var jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t \t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t \t\t//관리자 모든 회원보기\r\n");
      out.write("\t\t \t\t\r\n");
      out.write("\t\t \t\tvar main = null;\r\n");
      out.write("\t\t \t\tfor(var i in json.list){\r\n");
      out.write("\t\t \t\t\tconsole.log(json.list[i].customerId);\r\n");
      out.write("\t\t \t\tmain+='<tr><th>'+json.list[i].customerId+'</th>';\r\n");
      out.write("\t\t \t\tmain+='<th>'+decodeURIComponent(json.list[i].customerName)+'</th>';\r\n");
      out.write("\t\t \t\tmain+='<th>'+json.list[i].customerEmail+'</th>';\r\n");
      out.write("\t\t \t\tmain+='<th style=\"float:right;\"><button type=\"button\" onclick=\"withdraw(\\''+json.list[i].customerId+'\\');\" class=\"btn btn-outline-primary\" >강퇴</button></th></tr>';\r\n");
      out.write("\t\t \t\t}\r\n");
      out.write("\t\t \t\t\r\n");
      out.write("\t\t \t\t$('#tab1_main').html(main);\r\n");
      out.write("\t\t \t\t//페이징 처리\r\n");
      out.write("\t\t \t\tvar paging ='<th colspan=\"5\">';\r\n");
      out.write("\t\t \t\tif(currentPage<=1)\r\n");
      out.write("\t\t \t\t\t{\r\n");
      out.write("\t\t \t\t\tpaging+='[맨처음]&nbsp;';\r\n");
      out.write("\t\t \t\t\t}\r\n");
      out.write("\t\t \t\telse {\r\n");
      out.write("\t\t \t\t\t\r\n");
      out.write("\t\t \t\t\tpaging+='<a href=\"javascript:reviewPaging(1);\">[맨처음]</a>';\r\n");
      out.write("\t\t \t\t}\r\n");
      out.write("\t\t \t\tif ((currentPage - 10) < startPage && (currentPage - 10) >= 1) {\r\n");
      out.write("\t\t \t\t\tpaging+='<a href=\"javascript:reviewPaging('+(startPage-1)+');\">[prev]</a>';\r\n");
      out.write("\t\t \t\t} else {\r\n");
      out.write("\t\t \t\t\tpaging+='[prev]&nbsp;';\r\n");
      out.write("\t\t \t\t}\r\n");
      out.write("\t\t \t\tfor (var p = startPage; p <= endPage; p++) {\r\n");
      out.write("\t\t \t\t\tif (p == currentPage) {\r\n");
      out.write("\t\t \t\t\t\tpaging+='<font color=\"red\" size=\"4\"><b>['+p+']</b></font>';\r\n");
      out.write("\t\t \t\t} else {\r\n");
      out.write("\t\t \t\t\tpaging+='<a href=\"javascript:reviewPaging('+p+');\">'+p+'</a>';\r\n");
      out.write("\t\t \t\t}}\r\n");
      out.write("\r\n");
      out.write("\t\t \t\tif ((currentPage + 10) > endPage && (currentPage + 10) <= maxPage) {\r\n");
      out.write("\t\t \t\t\tpaging+=\r\n");
      out.write("\t\t \t'<a href=\"javascript:reviewPaging('+(endPage + 1)+')\">[next]</a>';\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \t\t} else {paging+='[next]&nbsp';}\r\n");
      out.write("\t\t \t\tif (currentPage >= maxPage) {\r\n");
      out.write("\t\t \t\t\tpaging+='[맨끝]&nbsp';\r\n");
      out.write("\t\t \t\t} else {\r\n");
      out.write("\t\t \t\t\tpaging+='<a href=\"javascript:reviewPaging('+maxPage+')\">[맨끝]</a>';\r\n");
      out.write("\t\t \t\t}\r\n");
      out.write("\t\t \t\tpaging+='</th>';\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \t\t\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \t\t$('#t_page').html(paging);\r\n");
      out.write("\r\n");
      out.write("\t\t \t},\r\n");
      out.write("\t\t \terror: function(jqXHR, textStatus, errorThrown) { \r\n");
      out.write("\t\t         console.log(jqXHR.responseText); \r\n");
      out.write("\t\t     } \t\r\n");
      out.write("\t\t });\r\n");
      out.write("\t }else{\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t location.href = \"/food/views/adminMy/admin_my.jsp\";\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t }\r\n");
      out.write("}\r\n");
      out.write("function reviewPaging(pageNum){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"/food/adminAllSearchList\",\r\n");
      out.write("\t\tdata : {page : pageNum},\r\n");
      out.write("\t\ttype : \"get\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\t  success: function(data){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\tstartPage =data.startPage;\r\n");
      out.write("\t\t\tendPage =data.endPage;\r\n");
      out.write("\t\t\tmaxPage = data.maxPage;\r\n");
      out.write("\t\t\tcurrentPage = data.currentPage;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t  var jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t//관리자 모든 회원보기\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar main = null;\r\n");
      out.write("\t\t\tfor(var i in json.list){\r\n");
      out.write("\t\t\t\tconsole.log(json.list[i].customerId);\r\n");
      out.write("\t\t\tmain+='<tr><th>'+json.list[i].customerId+'</th>';\r\n");
      out.write("\t\t\tmain+='<th>'+decodeURIComponent(json.list[i].customerName)+'</th>';\r\n");
      out.write("\t\t\tmain+='<th>'+json.list[i].customerEmail+'</th>';\r\n");
      out.write("\t\t\tmain+='<th style=\"float:right;\"><button type=\"button\" onclick=\"withdraw(\\''+json.list[i].customerId+'\\');\" class=\"btn btn-outline-primary\" >강퇴</button></th></tr>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#tab1_main').html(main);\r\n");
      out.write("\t\t\t//페이징 처리\r\n");
      out.write("\t\t\tvar paging ='<th colspan=\"5\">';\r\n");
      out.write("\t\t\tif(currentPage<=1)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\tpaging+='[맨처음]&nbsp;';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tpaging+='<a href=\"javascript:reviewPaging(1);\">[맨처음]</a>';\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ((currentPage - 10) < startPage && (currentPage - 10) >= 1) {\r\n");
      out.write("\t\t\t\tpaging+='<a href=\"javascript:reviewPaging('+(startPage-1)+');\">[prev]</a>';\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tpaging+='[prev]&nbsp;';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfor (var p = startPage; p <= endPage; p++) {\r\n");
      out.write("\t\t\t\tif (p == currentPage) {\r\n");
      out.write("\t\t\t\t\tpaging+='<font color=\"red\" size=\"4\"><b>['+p+']</b></font>';\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tpaging+='<a href=\"javascript:reviewPaging('+p+');\">'+p+'</a>';\r\n");
      out.write("\t\t\t}}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tif ((currentPage + 10) > endPage && (currentPage + 10) <= maxPage) {\r\n");
      out.write("\t\t\t\tpaging+=\r\n");
      out.write("\t\t'<a href=\"javascript:reviewPaging('+(endPage + 1)+')\">[next]</a>';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t} else {paging+='[next]&nbsp';}\r\n");
      out.write("\t\t\tif (currentPage >= maxPage) {\r\n");
      out.write("\t\t\t\tpaging+='[맨끝]&nbsp';\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tpaging+='<a href=\"javascript:reviewPaging('+maxPage+')\">[맨끝]</a>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tpaging+='</th>';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$('#t_page').html(paging);\r\n");
      out.write("\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(jqXHR, textStatus, errorThrown) { \r\n");
      out.write("            console.log(jqXHR.responseText); \r\n");
      out.write("        } \t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function adminSearchName(customer_seType, customer_seValue) {\r\n");
      out.write("\tconsole.log($('#customer_seValue').val());\r\n");
      out.write("\tconsole.log( $('[name=customer_seType]').val() );\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"/food/aSearchName\",\r\n");
      out.write("\t\tdata : {cSeValue : $('#customer_seValue').val(),\r\n");
      out.write("\t\t\tcSeType :$('[name=customer_seType]').val() },\r\n");
      out.write("\t\ttype : \"get\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\t  success: function(data){\r\n");
      out.write("\t\tstartPage =data.startPage;\r\n");
      out.write("\t\t\tendPage =data.endPage;\r\n");
      out.write("\t\t\tmaxPage = data.maxPage;\r\n");
      out.write("\t\t\tcurrentPage = data.currentPage;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  var jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t//관리자 모든 회원보기\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar main = null;\r\n");
      out.write("\t\t\tfor(var i in json.list){\r\n");
      out.write("\t\t\t\tconsole.log(json.list[i].customerId);\r\n");
      out.write("\t\t\tmain+='<tr><th>'+json.list[i].customerId+'</th>';\r\n");
      out.write("\t\t\tmain+='<th>'+decodeURIComponent(json.list[i].customerName)+'</th>';\r\n");
      out.write("\t\t\tmain+='<th>'+json.list[i].customerEmail+'</th>';\r\n");
      out.write("\t\t\tmain+='<th style=\"float:right;\"><button type=\"button\" onclick=\"withdraw(\\''+json.list[i].customerId+'\\');\" class=\"btn btn-outline-primary\" >강퇴</button></th></tr>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#tab1_main').html(main);\r\n");
      out.write("\t\t\t//페이징 처리\r\n");
      out.write("\t\t\tvar paging ='<th colspan=\"5\">';\r\n");
      out.write("\t\t\tif(currentPage<=1)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\tpaging+='[맨처음]&nbsp;';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tpaging+='<a href=\"javascript:reviewPaging(1);\">[맨처음]</a>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ((currentPage - 10) < startPage && (currentPage - 10) >= 1) {\r\n");
      out.write("\t\t\t\tpaging+='<a href=\"javascript:reviewPaging('+(startPage-1)+');\">[prev]</a>';\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tpaging+='[prev]&nbsp;';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfor (var p = startPage; p <= endPage; p++) {\r\n");
      out.write("\t\t\t\tif (p == currentPage) {\r\n");
      out.write("\t\t\t\t\tpaging+='<font color=\"red\" size=\"4\"><b>['+p+']</b></font>';\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tpaging+='<a href=\"javascript:reviewPaging('+p+');\">'+p+'</a>';\r\n");
      out.write("\t\t\t}}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tif ((currentPage + 10) > endPage && (currentPage + 10) <= maxPage) {\r\n");
      out.write("\t\t\t\tpaging+=\r\n");
      out.write("\t\t'<a href=\"javascript:reviewPaging('+(endPage + 1)+')\">[next]</a>';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t} else {paging+='[next]&nbsp';}\r\n");
      out.write("\t\t\tif (currentPage >= maxPage) {\r\n");
      out.write("\t\t\t\tpaging+='[맨끝]&nbsp';\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tpaging+='<a href=\"javascript:reviewPaging('+maxPage+')\">[맨끝]</a>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tpaging+='</th>';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$('#t_page').html(paging);\r\n");
      out.write("\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(jqXHR, textStatus, errorThrown) { \r\n");
      out.write("            console.log(jqXHR.responseText); \r\n");
      out.write("        } \t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check() {\r\n");
      out.write("\tvar start = $('[name=fes_start]').val();\r\n");
      out.write("\tvar end = $('[name=fes_end]').val();\r\n");
      out.write("\tvar file = $('[name=fes_image]').val();\r\n");
      out.write("\t//title이 비어있으면\r\n");
      out.write("\tif(fes_form.fes_title.value==\"\"){\r\n");
      out.write("\t\talert(\"제목을 입력하세요\");\r\n");
      out.write("\t\tfes_form.fes_title.focus();\r\n");
      out.write("\t\treturn false;\t\r\n");
      out.write("\t//주소가 비어있으면\t\r\n");
      out.write("\t}else if(fes_form.fes_addr.value==\"\"){\r\n");
      out.write("\t\talert(\"주소를 입력하세요\");\r\n");
      out.write("\t\tfes_form.fes_addr.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t//시작날짜가 끝 날짜보다 클 경우\t\r\n");
      out.write("\t}else if(Date.parse(start) > Date.parse(end)){\r\n");
      out.write("\t\talert(\"기간을 정확하게 입력하세요\");\r\n");
      out.write("\t\tfes_form.fes_end.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t//날짜가 비어있으면\t\r\n");
      out.write("\t}else if(!Date.parse(start) || !Date.parse(end)){\r\n");
      out.write("\t\talert(\"기간을 입력하세요\");\r\n");
      out.write("\t\tfes_form.fes_start.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t//주최측이 비어있으면\t\r\n");
      out.write("\t}else if(fes_form.fes_host.value==\"\"){\r\n");
      out.write("\t\talert(\"주최측 정보를 입력하세요\");\r\n");
      out.write("\t\tfes_form.fes_host.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t//연락처가 비어있으면\t\r\n");
      out.write("\t}else if(fes_form.fes_phone.value==\"\"){\r\n");
      out.write("\t\talert(\"연락처를 입력하세요\");\r\n");
      out.write("\t\tfes_form.fes_phone.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(!file){\r\n");
      out.write("\t\tvar ok = confirm(\"등록된 사진파일이 없습니다. 그대로 진행하시겠습니까?\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(오케이){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfes_form.fes_image.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else {\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"navcl\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\" style=\"padding-left: 0px;\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\" >\r\n");
      out.write("\t\t\t\t\t<li style=\"margin-right:10px;\"><a class=\"navbar-brand\" href=\"/food/index.jsp \">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/food/resources/images/LOGO_fooding.png\" style=\"width:65px; height:30px; \">\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li ><a href=\"/food/index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/slocation\">지역검색</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/flist\">푸드트럭</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/fes_show\">축제검색</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");
 if(loginMember==null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/views/logIn/logIn.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/views/signUp/select_signUp.jsp\"><span class=\"glyphicon glyphicon-edit\"></span> 회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t");
 } else if(loginMember instanceof Manager){
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a><span class=\"glyphicon glyphicon-user\"></span> ");
      out.print(((Manager)loginMember).getManager_Id() );
      out.write("님</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"/food/views/adminMy/admin_my.jsp\"><img alt=\"회원관리\" src=\"/food/resources/images/people.png\" width=\"15px\" height=\"15px\">회원관리</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/memberlogout\"><span class=\"glyphicon glyphicon-share\"></span>로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"header\" style=\"top: 50px\">\r\n");
      out.write("\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t<ul id=\"ul\" class=\"tabs\">\r\n");
      out.write("\t\t\t\t<li class=\"current\" data-tab=\"tab-1\"><a href=\"/food/views/adminMy/admin_my.jsp\" class=\"active\"><span class=\"icon fa-edit\">일반회원</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-2\"><a href=\"/food/blist\"><span class=\"icon fa-edit\">사업자 회원 </span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-3\"><a href=\"/food/bapprov\"><span class=\"icon fa-edit\">사업자 미승인회원</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-5\"><a href=\"/food/breject\"><span class=\"icon fa-edit\">사업자 거절회원</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-4\"><a href=\"#festival\"><span class=\"icon fa-edit\">축제정보등록</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-6\"><a href=\"/food/mtotal\"><span class=\"icon fa-edit\">통계</span></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"tab-1\" class=\"tab-content tab-1\">\r\n");
      out.write("\t\t<div  style=\"margin-left:15%; margin-right:15%; margin-top:3%; min-width:300px;\">\r\n");
      out.write("\t\t\t\t<!-- tab-1 시작 -->\r\n");
      out.write("  \t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<ul class=\"pagination\" >\r\n");
      out.write("\t<li class=\"page-item\"><h2>일반 회원 관리</h2>\r\n");
      out.write("\t<div style=\"border-bottom: 1px solid #bdbdbd; width: 1145px;\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t</ul></div>\r\n");
      out.write("\t<form  style=\"float:right;\" action=\"\" method=\"post\">\r\n");
      out.write("\t<select name=\"customer_seType\" >\r\n");
      out.write("\t\t\t<option value=\"customer_id\" selected> 아이디</option>\r\n");
      out.write("\t\t\t<option value=\"customer_name\" > 이름</option>\r\n");
      out.write("\t\t\t<option value=\"customer_email\"> 이메일</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\r\n");
      out.write("<input type=\"text\" id=\"customer_seValue\" name=\"customer_seValue\">&nbsp;<input type=\"button\" value=\"검색\" style=\"background:green; border:green; color:white;\" onclick =\"javascript: adminSearchName(customer_seType, customer_seValue);\"></form>\r\n");
      out.write("\t\r\n");
      out.write("\t\t <table class=\"table table-striped\">\r\n");
      out.write("    <thead>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th style=\"width:10%; min-width:100px;\" >아이디</th>\r\n");
      out.write("      \t<th style=\"width:10%; min-width:100px;\">이름</th>\r\n");
      out.write("      \t<th >이메일</th>\r\n");
      out.write("       \t<th style=\"width:8%\"> </th>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    \r\n");
      out.write("    <tbody id=\"tab1_main\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("  <tbody id=\"t_page\">\r\n");
      out.write("  \r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write(" <!-- tab-1끝 -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"tab-2\" class=\"tab-content tab-2\">\r\n");
      out.write("\t\t<div  style=\"margin-left:15%; margin-right:15%; margin-top:3%; min-width:300px;\">\r\n");
      out.write("\t\t\t<!-- tab-2 시작 -->\r\n");
      out.write("<div>\r\n");
      out.write("\t<ul class=\"pagination\" >\r\n");
      out.write("\t<li class=\"page-item\"><h2>사업자 회원 관리</h2>\r\n");
      out.write("<div style=\"border-bottom: 1px solid #bdbdbd; width: 1145px;\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("\t</ul></div>\r\n");
      out.write("\t<form  style=\"float:right;\" action=\"/food/searchblist\" method=\"post\">\r\n");
      out.write("\t<select name=\"seType\" >\r\n");
      out.write("\t\t\t<option value=\"business_id\" selected> 아이디</option>\r\n");
      out.write("\t\t\t<option value=\"business_name\" > 이름</option>\r\n");
      out.write("\t\t\t<option value=\"business_email\"> 이메일</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\r\n");
      out.write("<input type=\"text\" name=\"seValue\">&nbsp;<input type=\"submit\" value=\"검색\" style=\"background:green; border:green; color:white;\"></form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t <table class=\"table table-striped\">\r\n");
      out.write("    <thead>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th style=\"width:10%; min-width:100px;\" >아이디</th>\r\n");
      out.write("      \t<th style=\"width:10%; min-width:100px;\">이름</th>\r\n");
      out.write("      \t<th >이메일</th>\r\n");
      out.write("       \t<th style=\"width:8%\"> </th>\r\n");
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    \r\n");
      out.write("    <tbody style=\"text-align:center;\">\r\n");
      out.write("    ");

     int listCount=1;
	 int startPage=1;
	 int endPage=1;
	 int maxPage=1;
	 int currentPage=1;
	
	if(request.getAttribute("list") != null){
		ArrayList<Business> list =(ArrayList<Business>)request.getAttribute("list");  
		 listCount = ((Integer)request.getAttribute("listCount")).intValue();
		startPage = ((Integer)request.getAttribute("startPage")).intValue();
		 endPage = ((Integer)request.getAttribute("endPage")).intValue();
		 maxPage = ((Integer)request.getAttribute("maxPage")).intValue();			
		currentPage = ((Integer)request.getAttribute("currentPage")).intValue();	
		
		for(Business business:list) {
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>");
      out.print(business.getBusiness_Id());
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(business.getBusiness_Name());
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(business.getBusiness_Email());
      out.write("</th>\r\n");
      out.write("\t\t\t<th style=\"float:right;\"><input type=\"button\" onclick = \"compulWithDrawButton('");
      out.print(business.getBusiness_Id() );
      out.write("');\" class=\"btn btn-outline-primary\" value=\"강퇴\"></th>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
 }}else{
      out.write("\r\n");
      out.write("\t\t<tr style = \"background-color: white;\">\r\n");
      out.write("\t\t<td align=\"center\" colspan=\"4\" style=\"color:gray\">");
      out.print(request.getAttribute("noSearchArpproval") );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write(" \r\n");
      out.write("\t\t<hr style=\"margin-top:30px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"text-align:center; \">\r\n");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("\t[맨처음]&nbsp;\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/blist?currentPage=1\">[맨처음]</a>\r\n");
 } 
      out.write('\r');
      out.write('\n');
 if((currentPage - 10) < startPage 
		&& (currentPage - 10) >= 1){ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/blist?currentPage=");
      out.print( startPage - 1 );
      out.write("\">[prev]</a>\t\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t[prev]&nbsp;\r\n");
 } 
      out.write("\r\n");
      out.write("<!-- 현재 페이지가 포함된 그룹의 페이지 숫자 출력 -->\r\n");
 for(int p = startPage; p <= endPage; p++){ 
		if(p == currentPage){

      out.write("\r\n");
      out.write("\t<font color=\"red\" size=\"4\"><b>[");
      out.print( p );
      out.write("]</b></font>\r\n");
      out.write("\t");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/blist?currentPage=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
 }} 
      out.write("\r\n");
      out.write("\r\n");
 if((currentPage + 10) > endPage 
		&& (currentPage + 10) <= maxPage){ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/blist?currentPage=");
      out.print( endPage + 1 );
      out.write("\">[next]</a>\t\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t[next]&nbsp;\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("[맨끝]&nbsp;\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a  href=\"/food/blist?currentPage=");
      out.print( maxPage );
      out.write("\">[맨끝]</a>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br style=\"margin-top:20px;\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write(" <!-- tab-2끝 -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"tab-3\" class=\"tab-content tab-3\">\r\n");
      out.write("\t\t<div  style=\"margin-left:15%; margin-right:15%; margin-top:3%; min-width:300px;\">\r\n");
      out.write("\t\t\t<!-- tab-3 시작 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<ul class=\"pagination\" >\r\n");
      out.write("\t<li class=\"page-item\"><h2>사업자 미승인 회원</h2>\r\n");
      out.write("\t<div style=\"border-bottom: 1px solid #bdbdbd; width: 1145px;\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("\t</ul></div>\r\n");
      out.write("\t<form  style=\"float:right;\" action=\"/food/searchapproval\" method=\"post\">\r\n");
      out.write("\t<select name=\"seType\" style=\"height:21.5px;\">\r\n");
      out.write("\t\t\t<option value=\"business_id\" selected> 아이디</option>\r\n");
      out.write("\t\t\t<option value=\"business_name\" > 이름</option>\r\n");
      out.write("\t\t\t<option value=\"business_email\"> 이메일</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\r\n");
      out.write("<input type=\"text\" name=\"seValue\" style=\"vertical-align:top; \">&nbsp;<input type=\"submit\" value=\"검색\" style=\"background:green; vertical-align:top; border:green; color:white; height:21.5px; text-align:center \"></form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form method=\"post\" action=\"/food/approvbtn\" id =\"app\">\r\n");
      out.write("\t\t <table class=\"table table-striped\">\r\n");
      out.write("    <thead>\r\n");
      out.write("      <tr>\r\n");
      out.write("      <th style=\"width: 15%;\"><input id=\"delCheck\" type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\tname=\"delCheckAll\" value=null  >전체선택</th>\r\n");
      out.write("        <th style=\"width:10%; min-width:100px;\" >아이디</th>\r\n");
      out.write("      \t<th style=\"width:10%; min-width:100px;\">이름</th>\r\n");
      out.write("      \t<th >이메일</th>\r\n");
      out.write("      \t<th id=\"th_reject\" style=\"width:5%;\"></th>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody style=\"text-align:center;\">\r\n");
      out.write("    ");

 
	
	if(request.getAttribute("list") != null){
		ArrayList<Business> list =(ArrayList<Business>)request.getAttribute("list");  
		 listCount = ((Integer)request.getAttribute("listCount")).intValue();
		startPage = ((Integer)request.getAttribute("startPage")).intValue();
		 endPage = ((Integer)request.getAttribute("endPage")).intValue();
		 maxPage = ((Integer)request.getAttribute("maxPage")).intValue();			
		currentPage = ((Integer)request.getAttribute("currentPage")).intValue();	
		
		for(Business business:list) {
			
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<input id=\"ID");
      out.print(count );
      out.write("email\" type=\"checkbox\" name=\"business_email\" value=\"");
      out.print(business.getBusiness_Email());
      out.write("\" hidden = \"hidden\" >\r\n");
      out.write("\t\t\t<th style=\"width: 15%;\">\r\n");
      out.write("\t\t\t<input id=\"ID");
      out.print(count );
      out.write("\" type=\"checkbox\"\tname=\"delCheck\" value=\"");
      out.print(business.getBusiness_Id());
      out.write("\"></th>\r\n");
      out.write("\t\t\t<th>");
      out.print(business.getBusiness_Id());
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(business.getBusiness_Name());
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(business.getBusiness_Email());
      out.write("</th>\r\n");
      out.write("\t\t\t<!-- <th><p id=\"approvalbutton");
      out.print(business.getBusiness_Id());
      out.write("\"><input type=\"button\"  onclick = \"approvalbutton('");
      out.print(business.getBusiness_Id() );
      out.write("' ,'bapprov');\" class=\"btn btn-outline-primary\" value=\"승인\"></p></th> -->\r\n");
      out.write("\t\t\t<th ><p id=\"rejectbutton");
      out.print(business.getBusiness_Id());
      out.write("\"><input type=\"button\"  onclick = \"rejectbutton('");
      out.print(business.getBusiness_Id() );
      out.write("');\" class=\"btn btn-outline-primary\" value=\"거절\" ></p>\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t");
count++; 
      out.write("\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t<tr style = \"background-color: white; \">\r\n");
      out.write("\t\t<th align=\"center\" colspan=\"5\" style=\"color:gray\">");
      out.print(request.getAttribute("noSearchArpproval") );
      out.write("</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
 } 

		
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("  \r\n");
      out.write(" <hr style=\"margin-top:30px;\">\r\n");
 if(request.getAttribute("list") != null &&  ((ArrayList<Business>)request.getAttribute("list")).size() >0 ) {       
      out.write("\r\n");
      out.write("\t<input type =\"submit\" value=\"승인하기\" id =\"approvabtn\">\r\n");
      out.write("\t");
 } 
      out.write('\r');
      out.write('\n');
      out.write(' ');
if(request.getAttribute("apvbtnMessage")!= null ){ 
      out.write("\r\n");
      out.write("  <script> alert('");
      out.print(request.getAttribute("apvbtnMessage"));
      out.write("');</script>\r\n");
      out.write("  ");
 request.removeAttribute("apvbtnMessage"); }
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write(" </form>\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align:center; \">\r\n");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("\t[맨처음]&nbsp;\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/bapprov?currentPage=1\">[맨처음]</a>\r\n");
 } 
      out.write('\r');
      out.write('\n');
 if((currentPage - 10) < startPage 
		&& (currentPage - 10) >= 1){ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/bapprov?currentPage=");
      out.print( startPage - 1 );
      out.write("\">[prev]</a>\t\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t[prev]&nbsp;\r\n");
 } 
      out.write("\r\n");
      out.write("<!-- 현재 페이지가 포함된 그룹의 페이지 숫자 출력 -->\r\n");
 for(int p = startPage; p <= endPage; p++){ 
		if(p == currentPage){

      out.write("\r\n");
      out.write("\t<font color=\"red\" size=\"4\"><b>[");
      out.print( p );
      out.write("]</b></font>\r\n");
      out.write("\t");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/bapprov?currentPage=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
 }} 
      out.write("\r\n");
      out.write("\r\n");
 if((currentPage + 10) > endPage 
		&& (currentPage + 10) <= maxPage){ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/bapprov?currentPage=");
      out.print( endPage + 1 );
      out.write("\">[next]</a>\t\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t[next]&nbsp;\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("[맨끝]&nbsp;\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a  href=\"/food/bapprov?currentPage=");
      out.print( maxPage );
      out.write("\">[맨끝]</a>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br style=\"margin-top:20px;\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--  tab-3끝 -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"tab-4\" class=\"tab-content tab-4\">\r\n");
      out.write("<h2>&emsp;축제 정보 등록</h2>\r\n");
      out.write("\t\t<hr style=\"height: 1px; background: black; width: 850px; float: left\">\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"/food/fes_update\" method=\"post\"\r\n");
      out.write("\t\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 축제 이름 -->\r\n");
      out.write("\t\t\t<strong>축제 이름 </strong>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; <input\r\n");
      out.write("\t\t\t\tname=\"upfes_title\" value=\"\"\r\n");
      out.write("\t\t\t\ttype=\"text\" style=\"width: 200px; color: gray;\" required=\"required\"><font\r\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">&emsp;한글, 영문, 숫자\r\n");
      out.write("\t\t\t\t혼용가능(한글기준 10글자)</font> <br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 축제 장소 -->\r\n");
      out.write("\t\t\t<br> <br> <strong>축제 장소</strong>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<input name=\"upfes_addr\" value=\"\"\r\n");
      out.write("\t\t\t\ttype=\"text\" style=\"width: 300px; color: gray; margin-left: -4px;\" required=\"required\"><font\r\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">&emsp;한글, 영문, 숫자\r\n");
      out.write("\t\t\t\t혼용가능(한글기준 20글자)</font> <br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 축제 기간 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br> <br> <strong>축제 기간 </strong>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("\t\t\t<input type=\"date\" name=\"upfes_start\"\r\n");
      out.write("\t\t\t\tvalue=\"2018-01-01\"> ~ <input\r\n");
      out.write("\t\t\t\ttype=\"date\" name=\"upfes_end\"\r\n");
      out.write("\t\t\t\tvalue=\"2018-12-31\"> <font\r\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">달력을 잘보시고 체크해 주세요</font> <br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 주최측 -->\r\n");
      out.write("\t\t\t<br> <br> <strong>주최자(기관)명</strong>&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("\t\t\t<input name=\"upfes_host\" type=\"text\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 200px; color: gray; margin-left: -5px;\"\r\n");
      out.write("\t\t\t\tvalue=\"\" required=\"required\">&emsp;<font\r\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\"></font> <br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 축제 연락처 -->\r\n");
      out.write("\t\t\t<strong>축제 고객센터</strong>&emsp;&emsp;&emsp;&emsp; <input name=\"fes_phone\" type=\"text\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 200px; color: gray; margin-left: 2px;\"\r\n");
      out.write("\t\t\t\tplaceholder=\"ex) 02-123-4567\">&emsp;<font\r\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">\" - \" 생략가능</font> <br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 썸네일 사진 등록 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<strong style=\"float: left;\">썸네일 사진 </strong>&emsp;&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"file\" accept=\"image/*\" name=\"imgFile0\"\r\n");
      out.write("\t\t\t\tonchange=\"imgChange(0);\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\tname=\"upfes_image_ori\"\r\n");
      out.write("\t\t\t\tvalue=\"\"> <br>\r\n");
      out.write("\t\t\t<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; <img\r\n");
      out.write("\t\t\t\tid=\"img0\" style=\"width: 400px; height: 250px;\" alt=\"이미지를 등록하세요\"\r\n");
      out.write("\t\t\t\tsrc=\"/food/resources/images/festival/\">\r\n");
      out.write("\t\t\t<br><br><hr style=\"width: 850px; float: left\"><br><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 메인사진 등록 -->\r\n");
      out.write("\t<strong style=\"float: left;\">메인 사진 </strong>&emsp;&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("\t\t\t<input type=\"file\" accept=\"image/*\" name=\"imgFile1\" onchange=\"imgChange(1);\"> \r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"upfes_image_main\" value=\"\"> <br>\r\n");
      out.write("\t\t\t<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; \r\n");
      out.write("\t\t\t<img id=\"img1\" style=\"width: 400px; height: 250px;\" alt=\"이미지를 등록하세요\"\r\n");
      out.write("\t\t\t\tsrc=\"/food/resources/images/festival/\">\r\n");
      out.write("\t\t\t<br><br><hr style=\"width: 850px; float: left\"><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 축제사진 등록 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<strong style=\"float: left;\">축제 사진 </strong> <br> <br>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"사진 추가\" onclick=\"addImage() \">\r\n");
      out.write("\t\t\t&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"addImageDiv\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 등록하기 버튼 -->\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"margin-left: 30px\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"수정하기\" onclick=\"trySubmitBtn(); return false;\">\r\n");
      out.write("\t\t\t\t<input hidden=\"hidden\" id=\"modSubmit\" type=\"submit\" value=\"수정하기\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tfunction trySubmitBtn() {\r\n");
      out.write("\t\t\t\tif (imgCount > 0)\r\n");
      out.write("\t\t\t\t\t$('#modSubmit').click();\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\talert(\"사진을 최소 한 장 이상 등록하세요.\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- tab-5시작 -->\t\t\r\n");
      out.write("<div id=\"tab-5\" class=\"tab-content tab-5\">\r\n");
      out.write("<div  style=\"margin-left:15%; margin-right:15%; margin-top:3%; min-width:300px;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("<div>\r\n");
      out.write("\t<ul class=\"pagination\" >\r\n");
      out.write("\t<li class=\"page-item\"><h2>사업자 승인거절 회원</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("\t</ul></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t <table class=\"table table-striped\">\r\n");
      out.write("    <thead>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th style=\"width:10%; min-width:100px;\" >아이디</th>\r\n");
      out.write("      \t<th style=\"width:10%; min-width:100px;\">이름</th>\r\n");
      out.write("      \t<th >이메일</th>\r\n");
      out.write("      \t<th></th>\r\n");
      out.write("       \t\r\n");
      out.write("      </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    \r\n");
      out.write("    <tbody style=\"text-align:center;\">\r\n");
      out.write("    ");

   
	
	if(request.getAttribute("list") != null){
		ArrayList<Business> list =(ArrayList<Business>)request.getAttribute("list");  
		 listCount = ((Integer)request.getAttribute("listCount")).intValue();
		startPage = ((Integer)request.getAttribute("startPage")).intValue();
		 endPage = ((Integer)request.getAttribute("endPage")).intValue();
		 maxPage = ((Integer)request.getAttribute("maxPage")).intValue();			
		currentPage = ((Integer)request.getAttribute("currentPage")).intValue();	
		
		for(Business business:list) {
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<th>");
      out.print(business.getBusiness_Id());
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(business.getBusiness_Name());
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(business.getBusiness_Email());
      out.write("</th>\r\n");
      out.write("\t\t\t<th style=\"float:right;\"><input type=\"button\" onclick = \"againApprovalbutton('");
      out.print(business.getBusiness_Id() );
      out.write("','breject')\" class=\"btn btn-outline-primary\" value=\"재승인\"></th>\r\n");
      out.write("\t\t\t<th style=\"float:right;\"><input type=\"button\" onclick = \"deletebutton('");
      out.print(business.getBusiness_Id() );
      out.write("')\" class=\"btn btn-outline-primary\" value=\"삭제\"></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
 }}else{
      out.write("\r\n");
      out.write("\t\t<tr style = \"background-color: white;\">\r\n");
      out.write("\t\t<td align=\"center\" colspan=\"4\">");
      out.print(request.getAttribute("noSearchArpproval") );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write(" \r\n");
      out.write("\t\t<hr style=\"margin-top:30px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"text-align:center; \">\r\n");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("\t[맨처음]&nbsp;\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/breject?currentPage=1\">[맨처음]</a>\r\n");
 } 
      out.write('\r');
      out.write('\n');
 if((currentPage - 10) < startPage 
		&& (currentPage - 10) >= 1){ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/breject?currentPage=");
      out.print( startPage - 1 );
      out.write("\">[prev]</a>\t\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t[prev]&nbsp;\r\n");
 } 
      out.write("\r\n");
      out.write("<!-- 현재 페이지가 포함된 그룹의 페이지 숫자 출력 -->\r\n");
 for(int p = startPage; p <= endPage; p++){ 
		if(p == currentPage){

      out.write("\r\n");
      out.write("\t<font color=\"red\" size=\"4\"><b>[");
      out.print( p );
      out.write("]</b></font>\r\n");
      out.write("\t");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/breject?currentPage=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
 }} 
      out.write("\r\n");
      out.write("\r\n");
 if((currentPage + 10) > endPage 
		&& (currentPage + 10) <= maxPage){ 
      out.write("\r\n");
      out.write("\t<a href=\"/food/breject?currentPage=");
      out.print( endPage + 1 );
      out.write("\">[next]</a>\t\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t[next]&nbsp;\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("[맨끝]&nbsp;\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a  href=\"/food/breject?currentPage=");
      out.print( maxPage );
      out.write("\">[맨끝]</a>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br style=\"margin-top:20px;\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"tab-6\" class=\"tab-content tab-6\">\r\n");
      out.write("<div style=\"width:75%;\"><div class=\"chartjs-size-monitor\" style=\"position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;\"><div class=\"chartjs-size-monitor-expand\" style=\"position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;\"><div style=\"position:absolute;width:1000000px;height:1000000px;left:0;top:0\"></div></div><div class=\"chartjs-size-monitor-shrink\" style=\"position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;\"><div style=\"position:absolute;width:200%;height:200%;left:0; top:0\"></div></div></div>\r\n");
      out.write("\t\t<canvas id=\"canvas\" width=\"300\" height=\"200\" class=\"chartjs-render-monitor\" style=\"display: block; width: 483px; height: 241px;\"></canvas>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t");
Calendar calendar = Calendar.getInstance();
	String str[]=new String[8];
	for(int i=1; i<=7; i++){
		if(i>1){
		calendar.add(Calendar.DAY_OF_MONTH, -1);
		}else{
			calendar.add(Calendar.DAY_OF_MONTH, +0);
		}
		Date date = calendar.getTime();
		str[i]=new SimpleDateFormat("yyyy.MM.dd").format(date);
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tvar config = {\r\n");
      out.write("\t\t\ttype: 'bar',\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlabels: [\r\n");
      out.write("\t\t\t\t\t");
for(int i=7; i>=1; i--){
      out.write("\r\n");
      out.write("\t\t\t\t\t'");
      out.print(str[i]);
      out.write("',\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tdatasets: [{\r\n");
      out.write("\t\t\t\t\tlabel: '방문자 데이터',\r\n");
      out.write("\t\t\t\t\tbackgroundColor: window.chartColors.red,\r\n");
      out.write("\t\t\t\t\tborderColor: window.chartColors.red,\r\n");
      out.write("\t\t\t\t\tdata: [\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
if(request.getAttribute("tlist") != null){
						for(int i=1; i<=7; i++){
							System.out.print("나와라"+tlist.get(i).getT_total());
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(tlist.get(i).getT_total());
      out.write(",\r\n");
      out.write("\t\t\t\t\t\t");
}}else{}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\tfill: false,\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\toptions: {\r\n");
      out.write("\t\t\t\tresponsive: true,\r\n");
      out.write("\t\t\t\ttitle: {\r\n");
      out.write("\t\t\t\t\tdisplay: true,\r\n");
      out.write("\t\t\t\t\ttext: '방문자 그래프'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\ttooltips: {\r\n");
      out.write("\t\t\t\t\tmode: 'index',\r\n");
      out.write("\t\t\t\t\tintersect: false,\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\thover: {\r\n");
      out.write("\t\t\t\t\tmode: 'nearest',\r\n");
      out.write("\t\t\t\t\tintersect: true\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tscales: {\r\n");
      out.write("\t\t\t\t\txAxes: [{\r\n");
      out.write("\t\t\t\t\t\tdisplay: true,\r\n");
      out.write("\t\t\t\t\t\tscaleLabel: {\r\n");
      out.write("\t\t\t\t\t\t\tdisplay: true,\r\n");
      out.write("\t\t\t\t\t\t\tlabelString: 'Days'\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}],\r\n");
      out.write("\t\t\t\t\tyAxes: [{\r\n");
      out.write("\t\t\t\t\t\tdisplay: true,\r\n");
      out.write("\t\t\t\t\t\tscaleLabel: {\r\n");
      out.write("\t\t\t\t\t\t\tdisplay: true,\r\n");
      out.write("\t\t\t\t\t\t\tlabelString: 'Value'\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tticks: {\r\n");
      out.write("\t\t\t\t\t\t\tmin: 0,\r\n");
      out.write("\t\t\t\t\t\t\tmax: 1000,\r\n");
      out.write("\t\t\t\t\t\t\tstepSize: 100\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}]\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\twindow.onload = function() {\r\n");
      out.write("\t\t\tvar ctx = document.getElementById('canvas').getContext('2d');\r\n");
      out.write("\t\t\twindow.myLine = new Chart(ctx, config);\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"foot\" style=\"bottom: 0; position: absolute;\">FoodTruck &nbsp;Copyright @ iei.or.kr &nbsp; All Rights Reserved.</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
