/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2018-04-20 00:14:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.festival;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.security.auth.callback.ConfirmationCallback;
import member.model.vo.*;
import review.model.vo.*;
import java.util.*;
import reply.model.vo.*;
import festival.model.vo.*;

public final class festival_005fupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("reply.model.vo");
    _jspx_imports_packages.add("festival.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_packages.add("review.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.security.auth.callback.ConfirmationCallback");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

		Festival festival=(Festival)request.getAttribute("festival");
		ArrayList<String> imgList=(ArrayList<String>)request.getAttribute("img_list");

      out.write('\n');
      out.write('\n');

	//로그인 정보 가져오기
	Manager loginMember=null;
	
	if(session.getAttribute("loginMember")!=null)
	{
		loginMember = (Manager)session.getAttribute("loginMember");

	}
	else 
	{ //로그인 아니라면 index로 강제 소환
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\twindow.onload=function(){\n");
      out.write("\t\tlocation.href =\"/food/index.jsp\";\n");
      out.write("\t}\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t");
 }
	
//tab 정보 가져오기
	if (request.getAttribute("tab") != null) {
		

      out.write("\n");
      out.write("<script> \n");
      out.write("var tab = '");
      out.print(request.getAttribute("tab"));
      out.write("';\n");
      out.write("</script>\n");
 } else { 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\tvar tab = \"tab-1\";\n");
      out.write("</script>\n");

	}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>푸딩 푸드트럭 축제</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/top-menu.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/foot.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/left-menu.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/left-menu-tab.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/right-menu.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/modInfo.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/review.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/replay.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"/food/resources/js/jquery.min.js\"></script>\n");
      out.write("<script src=\"/food/resources/js/jquery.scrolly.min.js\"></script>\n");
      out.write("<script src=\"/food/resources/js/jquery.scrollzer.min.js\"></script>\n");
      out.write("<script src=\"/food/resources/js/skel.min.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"/food/resources/js/util.js\"></script>\n");
      out.write("<script src=\"/food/resources/js/main.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/food/resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("function deltImg(num)\n");
      out.write("{\t\n");
      out.write("\n");
      out.write("\t$('#imgSpan'+num).html(\"\");\n");
      out.write("\timgCount--;\n");
      out.write("}\n");
      out.write("\n");
      out.write("$(function() {\n");
      out.write("\t\n");
      out.write("\tif (tab != null) {\n");
      out.write("\t\t$('.tab-content').removeClass('current');\n");
      out.write("\t\t$('.tabs li').removeClass('current');\n");
      out.write("\t\t$('.tabs li a').removeClass('active');\n");
      out.write("\t\t$('#' + tab).addClass(' current');\n");
      out.write("\t\t$('[data-tab='+tab+'] a').addClass('active');\n");
      out.write("\t\tconsole.log('[data-tab='+tab+']');\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("});\n");
      out.write("\n");
      out.write("var imgNum = 2;\n");
      out.write("var imgCount = 0;\n");
      out.write("function addImage()\n");
      out.write("{\n");
      out.write("\n");
      out.write("\tvar newCode = '<span id=\"imgSpan'+imgNum+'\" ><input type=\"hidden\" name=\"oriImg\" value=\"\"><br><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<input type=\"file\" accept=\"image/*\" onchange=\"imgChange('+imgNum+');\" name=\"imgFile'+imgNum+'\" >&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<input type=\"button\" onclick=\"deltImg('+imgNum+');\" value=\"삭제하기\" >&nbsp;<input type=\"hidden\" name=\"fileTagName\" value=\"imgFile'+imgNum+'\" ><br><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<img id=\"img'+imgNum+'\" style=\"width:400px; height:250px;\" alt=\"이미지를 등록하세요\" src=\"#\"></span>';\n");
      out.write("\t\n");
      out.write("\t$('#addImageDiv').append(newCode);\n");
      out.write("\timgNum++;\n");
      out.write("\timgCount++;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function imgChange(num)\n");
      out.write("{\n");
      out.write("\tvar preview = document.querySelector('#img'+num);\n");
      out.write("\tvar file = document.querySelector('[name=imgFile'+num+']').files[0];\n");
      out.write("\tvar reader  = new FileReader(); \n");
      out.write("    reader.onloadend = function () { \n");
      out.write("           preview.src = reader.result; \n");
      out.write("    } \n");
      out.write("    if (file) { \n");
      out.write("           reader.readAsDataURL(file); \n");
      out.write("       } else { \n");
      out.write("           preview.src = \"\"; \n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function check() {\n");
      out.write("\tvar start = $('[name=upfes_start]').val();\n");
      out.write("\tvar end = $('[name=upfes_end]').val();\n");
      out.write("\tvar file = $('[name=upfes_image]').val();\n");
      out.write("\t//title이 비어있으면\n");
      out.write("\tif(upfes_form.upfes_title.value==\"\"){\n");
      out.write("\t\talert(\"제목을 입력하세요\");\n");
      out.write("\t\tupfes_form.upfes_title.focus();\n");
      out.write("\t\treturn false;\t\n");
      out.write("\t//주소가 비어있으면\t\n");
      out.write("\t}else if(upfes_form.upfes_addr.value==\"\"){\n");
      out.write("\t\talert(\"주소를 입력하세요\");\n");
      out.write("\t\tupfes_form.upfes_addr.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t//시작날짜가 끝 날짜보다 클 경우\t\n");
      out.write("\t}else if(Date.parse(start) > Date.parse(end)){\n");
      out.write("\t\talert(\"기간을 정확하게 입력하세요\");\n");
      out.write("\t\tupfes_form.upfes_end.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t//날짜가 비어있으면\t\n");
      out.write("\t}else if(!Date.parse(start) || !Date.parse(end)){\n");
      out.write("\t\talert(\"기간을 입력하세요\");\n");
      out.write("\t\tupfes_form.upfes_start.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t//주최측이 비어있으면\t\n");
      out.write("\t}else if(upfes_form.upfes_host.value==\"\"){\n");
      out.write("\t\talert(\"주최측 정보를 입력하세요\");\n");
      out.write("\t\tupfes_form.upfes_host.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t\t\n");
      out.write("\t}else if(upfes_form.upfes_phone.value==\"\"){\n");
      out.write("\t\talert(\"연락처를 입력하세요\");\n");
      out.write("\t\tupfes_form.upfes_phone.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t}else if(!file){\n");
      out.write("\t\tvar ok = confirm(\"등록된 사진파일이 없습니다. 그대로 진행하시겠습니까?\");\n");
      out.write("\t\t\n");
      out.write("\t\tif(ok){\n");
      out.write("\t\t\treturn true;\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\tupfes_form.upfes_image.focus();\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t}else {\n");
      out.write("\t\treturn true;\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"navcl\">\n");
      out.write("\t\t\t<nav class=\"navbar navbar-inverse\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\" style=\"padding-left: 0px;\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\" >\n");
      out.write("\t\t\t\t\t<li style=\"margin-right:10px;\"><a class=\"navbar-brand\" href=\"/food/index.jsp \">\n");
      out.write("\t\t\t\t\t\t<img src=\"/food/resources/images/LOGO_fooding.png\" style=\"width:65px; height:30px; \">\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t<li ><a href=\"/food/index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/slocation\">지역검색</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/flist\">푸드트럭</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"/food/fes_show\">축제검색</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t");
 if(loginMember==null){ 
      out.write("\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/views/logIn/logIn.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/views/signUp/select_signUp.jsp\"><span class=\"glyphicon glyphicon-edit\"></span> 회원가입</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t");
 } else if(loginMember instanceof Manager){
      out.write("\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t<li><a><span class=\"glyphicon glyphicon-user\"></span> ");
      out.print(((Manager)loginMember).getManager_Id() );
      out.write("님</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/views/adminMy/admin_my.jsp\"><img alt=\"회원관리\" src=\"/food/resources/images/people.png\" width=\"15px\" height=\"15px\">회원관리</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/memberlogout\"><span class=\"glyphicon glyphicon-share\"></span>로그아웃</a></li>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"header\" style=\"top: 50px\">\n");
      out.write("\t\t<nav id=\"nav\">\n");
      out.write("\t\t\t<ul id=\"ul\" class=\"tabs\">\n");
      out.write("\t\t\t\t<li class=\"current\" data-tab=\"tab-1\"><a href=\"#\" class=\"active\"><span class=\"icon fa-edit\">축제정보수정</span></a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</nav>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"tab-1\" class=\"tab-content tab-1\">\n");
      out.write("  \t\n");
      out.write("\t<h2>&emsp;축제 정보 수정</h2>\n");
      out.write("\t\t\t<hr style=\"height: 1px; background: black; width: 850px; float: left\">\n");
      out.write("\t\t\t<br> <br>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<form action=\"/food/fes_update\" name=\"upfes_form\" onsubmit=\"return check()\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"fNum\" value=\"");
      out.print( festival.getFestival_No());
      out.write("\">\n");
      out.write("\t\t\t\t\t<!-- 축제 이름 -->\n");
      out.write("\t\t\t<strong>축제 이름 </strong>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; <input\n");
      out.write("\t\t\t\tname=\"upfes_title\" value=\"");
      out.print( festival.getFestival_Name() );
      out.write("\"\n");
      out.write("\t\t\t\ttype=\"text\" style=\"width: 200px; color: gray;\"><font\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">&emsp;한글, 영문, 숫자\n");
      out.write("\t\t\t\t혼용가능(한글기준 10글자)</font> <br> <br>\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- 축제 장소 -->\n");
      out.write("\t\t\t<br> <br> <strong>축제 장소</strong>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t<input name=\"upfes_addr\" value=\"");
      out.print(festival.getFestival_Addr() );
      out.write("\"\n");
      out.write("\t\t\t\ttype=\"text\" style=\"width: 300px; color: gray; margin-left: -4px;\"><font\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">&emsp;한글, 영문, 숫자\n");
      out.write("\t\t\t\t혼용가능(한글기준 20글자)</font> <br> <br>\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- 축제 기간 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<br> <br> <strong>축제 기간 </strong>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\n");
      out.write("\t\t\t<input type=\"date\" name=\"upfes_start\"\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(festival.getFestival_Date_Start() );
      out.write("\"> ~ <input\n");
      out.write("\t\t\t\ttype=\"date\" name=\"upfes_end\"\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(festival.getFestival_Date_End() );
      out.write("\"> <font\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">달력을 잘보시고 체크해 주세요</font> <br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- 주최측 -->\n");
      out.write("\t\t\t<br> <br> <strong>주최자(기관)명</strong>&emsp;&emsp;&emsp;&emsp;\n");
      out.write("\t\t\t<input name=\"upfes_host\" type=\"text\"\n");
      out.write("\t\t\t\tstyle=\"width: 200px; color: gray; margin-left: -5px;\"\n");
      out.write("\t\t\t\tvalue=\"");
      out.print( festival.getFestival_Host());
      out.write("\">&emsp;<font\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">\" - \" 생략가능</font> <br> <br>\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\n");
      out.write("\t\t\t<br> <br>\n");
      out.write("\n");
      out.write("\t\t\t<!-- 축제 연락처 -->\n");
      out.write("\t\t\t<strong>축제 고객센터</strong>&emsp;&emsp;&emsp;&emsp; <input name=\"fes_phone\" type=\"text\"\n");
      out.write("\t\t\t\tstyle=\"width: 200px; color: gray; margin-left: 2px;\"\n");
      out.write("\t\t\t\tplaceholder=\"ex) 02-123-4567\" value=\"");
      out.print(festival.getFestival_Phone());
      out.write("\">&emsp;<font\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">\" - \" 생략가능</font> <br> <br>\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\n");
      out.write("\t\t\t<br> <br>\n");
      out.write("\n");
      out.write("\t\t\t<!-- 썸네일 사진 등록 -->\n");
      out.write("\n");
      out.write("\t\t\t<strong style=\"float: left;\">썸네일 사진 </strong>&emsp;&emsp;&emsp;&emsp;&emsp;\n");
      out.write("\n");
      out.write("\t\t\t<input type=\"file\" accept=\"image/*\" name=\"imgFile0\"\n");
      out.write("\t\t\t\tonchange=\"imgChange(0);\"> <input type=\"hidden\"\n");
      out.write("\t\t\t\tname=\"upfes_image_ori\"\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(festival.getFestival_Image_File() );
      out.write("\"> <br>\n");
      out.write("\t\t\t<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; <img\n");
      out.write("\t\t\t\tid=\"img0\" style=\"width: 400px; height: 250px;\" alt=\"이미지를 등록하세요\"\n");
      out.write("\t\t\t\tsrc=\"/food/resources/images/festival/");
      out.print(festival.getFestival_Image_File() );
      out.write("\">\n");
      out.write("\t\t\t<br><br><hr style=\"width: 850px; float: left\"><br><br>\n");
      out.write("\n");
      out.write("\t\t\t<!-- 메인사진 등록 -->\n");
      out.write("\t<strong style=\"float: left;\">메인 사진 </strong>&emsp;&emsp;&emsp;&emsp;&emsp;\n");
      out.write("\t\t\t<input type=\"file\" accept=\"image/*\" name=\"imgFile1\" onchange=\"imgChange(1);\"> \n");
      out.write("\t\t\t<input type=\"hidden\" name=\"upfes_image_main\" value=\"");
      out.print(festival.getFestival_Image_Main() );
      out.write("\"> <br>\n");
      out.write("\t\t\t<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; \n");
      out.write("\t\t\t<img id=\"img1\" style=\"width: 400px; height: 250px;\" alt=\"이미지를 등록하세요\"\n");
      out.write("\t\t\t\tsrc=\"/food/resources/images/festival/");
      out.print(festival.getFestival_Image_Main() );
      out.write("\">\n");
      out.write("\t\t\t<br><br><hr style=\"width: 850px; float: left\"><br><br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<!-- 축제사진 등록 -->\n");
      out.write("\n");
      out.write("\t\t\t<strong style=\"float: left;\">축제 사진 </strong> <br> <br>\n");
      out.write("\t\t\t<input type=\"button\" value=\"사진 추가\" onclick=\"addImage() \">\n");
      out.write("\t\t\t&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"addImageDiv\">\n");
      out.write("\t\t\t\t");
for(String s : imgList) {
      out.write("\n");
      out.write("\t\t\t\t<script>\n");
      out.write("\t\t\tconsole.log(\"");
      out.print(s);
      out.write("\");\n");
      out.write("\t\t\tvar newCode = '<span id=\"imgSpan'+imgNum+'\" ><input type=\"hidden\" name=\"oriImg\" value=\"");
      out.print(s);
      out.write("\"><br><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<input type=\"file\" accept=\"image/*\" onchange=\"imgChange('+imgNum+');\" name=\"imgFile'+imgNum+'\" >&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<input type=\"button\" onclick=\"deltImg('+imgNum+');\" value=\"삭제하기\" >&nbsp;<input type=\"hidden\" name=\"fileTagName\" value=\"imgFile'+imgNum+'\" ><br><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<img id=\"img'+imgNum+'\" style=\"width:400px; height:250px;\" alt=\"이미지를 등록하세요\" src=\"/food/resources/images/festival/");
      out.print(s);
      out.write("\"></span>';\n");
      out.write("\t\t\t\t\tdocument.write(newCode);\n");
      out.write("\t\t\t\t\timgNum++;\n");
      out.write("\t\t\t\t\timgCount++;\n");
      out.write("\t\t\t\t</script>\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- 등록하기 버튼 -->\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\n");
      out.write("\t\t\t<div style=\"margin-left: 30px\">\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"수정하기\" onclick=\"trySubmitBtn()\">\n");
      out.write("\t\t\t\t<input hidden=\"hidden\" id=\"modSubmit\" type=\"submit\" value=\"수정하기\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\tfunction trySubmitBtn() {\n");
      out.write("\t\t\t\tif (imgCount > 0)\n");
      out.write("\t\t\t\t\t$('#modSubmit').click();\n");
      out.write("\t\t\t\telse\n");
      out.write("\t\t\t\t\talert(\"사진을 최소 한 장 이상 등록하세요.\");\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\t</div>\n");
      out.write(" \n");
      out.write("\t<div class=\"foot\" style=\"bottom: 0; position: absolute;\">FoodTruck &nbsp;Copyright @ iei.or.kr &nbsp; All Rights Reserved.</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
