/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2018-04-19 23:32:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.food_005fTruck;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;
import java.util.*;
import foodtruck.model.vo.*;

public final class food_005fTruck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("foodtruck.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   ArrayList<Foodtruck> list = null;
   if (request.getAttribute("list") != null) {
      list = (ArrayList<Foodtruck>) request.getAttribute("list");
   }
   ArrayList<FoodTop3> top3List = null;
   if( request.getAttribute("top3List")!=null)
   {
      top3List = (ArrayList<FoodTop3>)request.getAttribute("top3List");
   }
   Member loginMember = null;
   if (session.getAttribute("loginMember") instanceof Business) {
      loginMember = (Business) session.getAttribute("loginMember");
   } else if (session.getAttribute("loginMember") instanceof Customer) {
      loginMember = (Customer) session.getAttribute("loginMember");
   } else if (session.getAttribute("loginMember") instanceof Manager) {
      loginMember = (Manager) session.getAttribute("loginMember");
   }
   
   
   ArrayList<FoodTop3> riceTop3List = null;
   ArrayList<FoodTop3> snackTop3List= null;
   ArrayList<FoodTop3> desertTop3List =null;
   if(request.getAttribute("riceTop3List")!=null)
   { 
      System.out.println("riceTop3List 오닝");
      riceTop3List=(ArrayList<FoodTop3>)request.getAttribute("riceTop3List");
      snackTop3List=(ArrayList<FoodTop3>)request.getAttribute("snackTop3List");
      desertTop3List=(ArrayList<FoodTop3>)request.getAttribute("desertTop3List");
   }
   

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>푸딩 푸드트럭 정보</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/top-menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/foot.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/location.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("   src=\"/food/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var topcount=0;\r\n");
      out.write("\r\n");
      out.write("var riceTop3List=[\"\",\"\",\"\"];\r\n");
      out.write("var riceTop3NameList=[\"\",\"\",\"\"];\r\n");
      out.write("var riceTop3BsIdList=[\"\",\"\",\"\"];\r\n");
      out.write("\r\n");
      out.write("var snackTop3List=[\"\",\"\",\"\"];\r\n");
      out.write("var snackTop3NameList=[\"\",\"\",\"\"];\r\n");
      out.write("var snackTop3BsIdList=[\"\",\"\",\"\"];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var desertTop3List=[\"\",\"\",\"\"];\r\n");
      out.write("var desertTop3NameList=[\"\",\"\",\"\"];\r\n");
      out.write("var desertTop3BsIdList=[\"\",\"\",\"\"];\r\n");
      out.write("\r\n");
for(FoodTop3 ft3 : riceTop3List){
      out.write("\r\n");
      out.write("   riceTop3List[topcount%3]=\"/food/resources/images/foodtruck/");
      out.print(ft3.getTruckImg());
      out.write("\";\r\n");
      out.write("   riceTop3NameList[topcount%3]=\"");
      out.print(ft3.getTruckName());
      out.write("\"\r\n");
      out.write("   riceTop3BsIdList[topcount%3]=\"");
      out.print(ft3.getBusinessId());
      out.write("\"\r\n");
      out.write("   topcount++;\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
for(FoodTop3 ft3 : snackTop3List){
      out.write("\r\n");
      out.write("   snackTop3List[topcount%3]=\"/food/resources/images/foodtruck/");
      out.print(ft3.getTruckImg());
      out.write("\";\r\n");
      out.write("   snackTop3NameList[topcount%3]=\"");
      out.print(ft3.getTruckName());
      out.write("\"\r\n");
      out.write("   snackTop3BsIdList[topcount%3]=\"");
      out.print(ft3.getBusinessId());
      out.write("\"\r\n");
      out.write("\r\n");
      out.write("   topcount++;\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
for(FoodTop3 ft3 : desertTop3List){
      out.write("\r\n");
      out.write("   desertTop3List[topcount%3]=\"/food/resources/images/foodtruck/");
      out.print(ft3.getTruckImg());
      out.write("\";\r\n");
      out.write("   desertTop3NameList[topcount%3]=\"");
      out.print(ft3.getTruckName());
      out.write("\"\r\n");
      out.write("   desertTop3BsIdList[topcount%3]=\"");
      out.print(ft3.getBusinessId());
      out.write("\"\r\n");
      out.write("   topcount++;\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("   \r\n");
      out.write("   $(\"#sidebox\").css(\"top\",290);\r\n");
      out.write("    var currentPosition = parseInt($(\"#sidebox\").css(\"top\")); \r\n");
      out.write("    $(window).scroll(function() { \r\n");
      out.write("       var position = $(window).scrollTop(); \r\n");
      out.write("       $(\"#sidebox\").stop().animate({\"top\":position+currentPosition+\"px\"},500); \r\n");
      out.write("       if ($(this).scrollTop() > 300) {\r\n");
      out.write("\r\n");
      out.write("            $(\"#sidebox\").css(\"margin-top\", 0);\r\n");
      out.write("            //$(\"#side_1\").css(\"margin-top\", \"10px\");\r\n");
      out.write("            //$(\"#side_1\").css(\"bottom\", \"600px\");\r\n");
      out.write("\r\n");
      out.write("            }else {\r\n");
      out.write("               $(\"#sidebox\").css(\"top\", \"462px\");\r\n");
      out.write("\r\n");
      out.write("            }    \r\n");
      out.write("    \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("//onload closed   \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var jj=0;\r\n");
      out.write("\r\n");
      out.write("setInterval(function()  {\r\n");
      out.write("   console.log(topcount);\r\n");
      out.write("   \r\n");
      out.write("   $(\"#top3img1\").prop(\"src\",riceTop3List[topcount%3]);\r\n");
      out.write("   $(\"#a_tag_top1\").prop(\"href\",'foodtruckdetail?bId='+riceTop3BsIdList[topcount%3]);\r\n");
      out.write("   $(\"#nametag_top1\").html(\"식사류 | <strong>\"+riceTop3NameList[topcount%3])+\"</strong>\";\r\n");
      out.write("   \r\n");
      out.write("   $(\"#top3img2\").prop(\"src\",snackTop3List[topcount%3]);\r\n");
      out.write("   $(\"#a_tag_top2\").prop(\"href\",'foodtruckdetail?bId='+snackTop3BsIdList[topcount%3]);\r\n");
      out.write("   $(\"#nametag_top2\").html(\"간식류 | <strong>\"+snackTop3NameList[topcount%3])+\"</strong>\";\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   $(\"#top3img3\").prop(\"src\",desertTop3List[topcount%3]);\r\n");
      out.write("   $(\"#a_tag_top3\").prop(\"href\",'foodtruckdetail?bId='+desertTop3BsIdList[topcount%3]);\r\n");
      out.write("   $(\"#nametag_top3\").html(\"디저트류 | <strong>\"+desertTop3NameList[topcount++%3])+\"</strong>\";\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   console.log(topcount);\r\n");
      out.write("   \r\n");
      out.write("}, 2000 );\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
int cnt = 0;
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   ");
if(loginMember instanceof Business){
      out.write("\r\n");
      out.write("   $.ajax({\r\n");
      out.write("         url : \"/food/NY\",\r\n");
      out.write("         data : {\r\n");
      out.write("           \r\n");
      out.write("               userid : \"");
      out.print(((Business)loginMember).getBusiness_Id());
      out.write("\"\r\n");
      out.write("            \r\n");
      out.write("         },\r\n");
      out.write("         type : 'post',\r\n");
      out.write("         success : function(data) {\r\n");
      out.write("           \r\n");
      out.write("            onoffState=data;\r\n");
      out.write("            if(data == 'Y'){//장사시작인 상태\r\n");
      out.write("               \r\n");
      out.write("                  $(\".gb\").hide();\r\n");
      out.write("                  $(\".rb\").show();\r\n");
      out.write("              \r\n");
      out.write("            }else {//장사 종료인 상태\r\n");
      out.write("              \r\n");
      out.write("               $(\".rb\").hide();\r\n");
      out.write("               $(\".gb\").show();\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   ");
}
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function onoff(){\r\n");
      out.write("   \r\n");
      out.write("      $.ajax({\r\n");
      out.write("            url : \"/food/onoff\",\r\n");
      out.write("            data : {\r\n");
      out.write("           state: onoffState,\r\n");
      out.write("               ");
if(loginMember instanceof Business){
      out.write("\r\n");
      out.write("                  'userid' : \"");
      out.print(((Business)loginMember).getBusiness_Id());
      out.write("\"\r\n");
      out.write("               ");
}
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            },\r\n");
      out.write("         type : 'post',\r\n");
      out.write("         success : function(data) {\r\n");
      out.write("          \r\n");
      out.write("            if(data == 1){\r\n");
      out.write("               alert(\"장사를 시작합니다\");\r\n");
      out.write("               onoffState='Y';\r\n");
      out.write("               $(\"#graybutton\").attr(\"src\", \"/food/resources/images/redbutton.png\");\r\n");
      out.write("               \r\n");
      out.write("               $(\".gb\").hide();\r\n");
      out.write("               $(\".rb\").show();\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("            }else if(data == 2){\r\n");
      out.write("               alert(\"장사를 종료합니다\");\r\n");
      out.write("               onoffState='N';\r\n");
      out.write("               $(\"#graybutton\").attr(\"src\", \"/food/resources/images/graybutton.png\");\r\n");
      out.write("               \r\n");
      out.write("               $(\".rb\").hide();\r\n");
      out.write("               $(\".gb\").show();\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("   \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function searchAutoComplete()\r\n");
      out.write("{\r\n");
      out.write("   $.ajax({\r\n");
      out.write("      url : \"/food/searchautocomplete\",\r\n");
      out.write("      type : \"post\",\r\n");
      out.write("      dataType : \"json\",\r\n");
      out.write("      data : {\r\n");
      out.write("         seType : $('#seType').val(),\r\n");
      out.write("         seValue : $('#seValue').val()\r\n");
      out.write("      },\r\n");
      out.write("      success : function(data){\r\n");
      out.write("         var jsonStr = JSON.stringify(data);\r\n");
      out.write("         var json = JSON.parse(jsonStr);\r\n");
      out.write("         \r\n");
      out.write("         var autoCode =\"\";\r\n");
      out.write("         for(var i in json.list)\r\n");
      out.write("            {\r\n");
      out.write("            autoCode += \" <option value='\"+json.list[i].values+\"'>\"+json.list[i].values+\"</option>  \";\r\n");
      out.write("            }\r\n");
      out.write("         $('#autoCompleteSelect').html(autoCode);\r\n");
      out.write("         \r\n");
      out.write("      },\r\n");
      out.write("      error : function(){\r\n");
      out.write("         console.log(\"자동완성 ajax 에러\");\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("   //검색어 자동완성~!^~%\r\n");
      out.write("$('#seValue').keyup(function(){\r\n");
      out.write("   searchAutoComplete();\r\n");
      out.write("   \r\n");
      out.write("});\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("$('#autoCompleteSelect').click(function(){\r\n");
      out.write("   $('#seValue').val($('#autoCompleteSelect').val());\r\n");
      out.write("});   \r\n");
      out.write("   \r\n");
      out.write("$('#ctType').change( getTruckList );\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   $(\"input[name=sevalue]\").keydown(function (key) {\r\n");
      out.write("       \r\n");
      out.write("        if(key.keyCode == 13){//키가 13이면 실행 (엔터는 13)\r\n");
      out.write("           getTruckList();\r\n");
      out.write("        }\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function getTruckList()\r\n");
      out.write("{\r\n");
      out.write("   \r\n");
      out.write("    $.ajax({\r\n");
      out.write("      url : \"/food/trucksearchlist\",\r\n");
      out.write("      type : \"post\",\r\n");
      out.write("      data : {ctType : $('#ctType').val(),\r\n");
      out.write("            seType : $('#seType').val(),\r\n");
      out.write("            seValue : $('#seValue').val()\r\n");
      out.write("         },\r\n");
      out.write("   dataType: \"json\",\r\n");
      out.write("   success : function(data){ \r\n");
      out.write("   \r\n");
      out.write("      var jsonStr = JSON.stringify(data);\r\n");
      out.write("      var json = JSON.parse(jsonStr);\r\n");
      out.write("      \r\n");
      out.write("      var htmlCode = \"\";\r\n");
      out.write("      for(var i in json.list)\r\n");
      out.write("         {   if(i%3==0){\r\n");
      out.write("            htmlCode += '<tr style=\"border: 1px solid #BDBDBD\">';}\r\n");
      out.write("            htmlCode += '<td style=\"border: 1px solid #BDBDBD; width: 33%;\">';\r\n");
      out.write("            htmlCode += '<a href=\"foodtruckdetail?bId='+json.list[i].bsId+'\">';\r\n");
      out.write("            htmlCode += '<img src=\"/food/resources/images/foodtruck/'+json.list[i].tImg+'\" style=\"width: 100%; padding: 0px;\"></img></a>';\r\n");
      out.write("           if(json.list[i].tLive== \"Y\"){\r\n");
      out.write("            htmlCode += '<h3 style=\"text-align: center\"><img id=\"blink_on\" width=\"20px\"height=\"auto\" src=\"/food/resources/images/btn_on.png\">'+decodeURIComponent((json.list[i].tName).replace(/\\+/g, '%20'))+'</h3>';\r\n");
      out.write("            \r\n");
      out.write("           }else{\r\n");
      out.write("              htmlCode += ' <h3 style=\"text-align: center\">'+decodeURIComponent((json.list[i].tName).replace(/\\+/g, '%20'))+'</b></span> </center>'; \r\n");
      out.write("           }\r\n");
      out.write("            htmlCode += '<h5 style=\"text-align: center\">'+decodeURIComponent((json.list[i].tMainMenu).replace(/\\+/g, '%20'))+'</h5></td>';\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("            if ( i % 3 == 2 )\r\n");
      out.write("               {\r\n");
      out.write("               htmlCode += \"</tr>\";\r\n");
      out.write("               }\r\n");
      out.write("            if( i==(json.list.length -1) )\r\n");
      out.write("               {\r\n");
      out.write("               for(j=i%3;j<3;j++)\r\n");
      out.write("                  {htmlCode+=\"<td></td>\";}\r\n");
      out.write("               htmlCode+=\"</tr>\";\r\n");
      out.write("               }\r\n");
      out.write("         }\r\n");
      out.write("   $('#truck_table').html(htmlCode);\r\n");
      out.write("   console.log(htmlCode);\r\n");
      out.write("   },error: function(jqXHR, textStatus, errorThrown) { \r\n");
      out.write("        console.log(jqXHR.responseText); \r\n");
      out.write("    }    \r\n");
      out.write("   \r\n");
      out.write("   });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#blink_on {\r\n");
      out.write("   animation:blink 1.0s ease-in-out infinite alternate;\r\n");
      out.write("   animation-duration: 1000ms;\r\n");
      out.write("    animation-iteration-count: infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes blink{\r\n");
      out.write("    0% {opacity:0.3;}\r\n");
      out.write("    100% {opacity:1;}\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebox {background-color:white; position:absolute; width:150%; top:470px; right:50px; padding: 0px; }\r\n");
      out.write("\r\n");
      out.write(".main {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 2000px;\r\n");
      out.write("}\r\n");
      out.write(".main .content {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    height: 2000px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    background-color: #EEEEEE;\r\n");
      out.write("}\r\n");
      out.write(".main .left {\r\n");
      out.write("    float: right;\r\n");
      out.write("    width: 25%;\r\n");
      out.write("    height: 2000px;\r\n");
      out.write("}\r\n");
      out.write(".main .left .menu {\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    height: 165px;\r\n");
      out.write("    background-color: #424242;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("}\r\n");
      out.write(".main .left .menu ul {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    color: #EEEEEE;\r\n");
      out.write("    padding-left: 0px;\r\n");
      out.write("}\r\n");
      out.write(".main .left .menu ul li {margin:10px;}\r\n");
      out.write("\r\n");
      out.write("/* 메인사진 */\r\n");
      out.write("#mainPhoto {\r\n");
      out.write("   background-image: url(\"/food/resources/images/FOODING2.jpg\");\r\n");
      out.write("   background-size: cover;\r\n");
      out.write("   background-position: center;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   height: 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-sm-4 {\r\n");
      out.write("   border: 2px solid #DCDCDC;\r\n");
      out.write("   width: 30%;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   margin-left: 2.5%;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <!-- 상단 네비게이션 바 -->\r\n");
      out.write("   <div class=\"navcl\">\r\n");
      out.write("      <nav class=\"navbar navbar-inverse\">\r\n");
      out.write("         \r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"myNavbar\" style=\"padding-left: 0px;\">\r\n");
      out.write("               <ul class=\"nav navbar-nav\" >\r\n");
      out.write("               <li style=\"margin-right:10px;\"><a class=\"navbar-brand\" href=\"/food/index.jsp \">\r\n");
      out.write("                  <img src=\"/food/resources/images/LOGO_fooding.png\" style=\"width:65px; height:30px; \">\r\n");
      out.write("                  </a></li>\r\n");
      out.write("               <li ><a href=\"/food/index.jsp\">Home</a></li>\r\n");
      out.write("               <li><a href=\"/food/slocation\">지역검색</a></li>\r\n");
      out.write("               <li class=\"active\"><a href=\"/food/flist\">푸드트럭</a></li>\r\n");
      out.write("               <li><a href=\"/food/fes_show\">축제검색</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               ");
 if(loginMember==null){ 
      out.write("\r\n");
      out.write("               <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                  <li><a href=\"/food/views/logIn/logIn.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("                  <li><a href=\"/food/views/signUp/select_signUp.jsp\"><span class=\"glyphicon glyphicon-edit\"></span> 회원가입</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               ");
 } else if(loginMember instanceof Customer){
      out.write("\r\n");
      out.write("               <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("               <li><a><span class=\"glyphicon glyphicon-user\"></span> ");
      out.print(((Customer)loginMember).getCustomer_Id() );
      out.write("님</a></li>\r\n");
      out.write("               <li><a href=\"/food/views/userMy/user_my.jsp\"><span class=\"glyphicon glyphicon-th-list\"></span>내 정보 보기</a></li>\r\n");
      out.write("               <li><a href=\"/food/memberlogout\"><span class=\"glyphicon glyphicon-share\"></span>로그아웃</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               ");
 } else if(loginMember instanceof Business){
      out.write("\r\n");
      out.write("                  <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\r\n");
      out.write("                  <li class=\"gb\" ><a class=\"gb\"  href=\"javascript: onoff();\"><img class=\"gb\" id=\"graybutton\"  alt=\"회색버튼\" src=\"/food/resources/images/graybutton.png\" width=\"15px\" height=\"15px\"><span class=\"glyphicon gb\"></span>장사 시작</a></li>                  \r\n");
      out.write("                  <li class=\"rb\" ><a class=\"rb\"  href=\"javascript: onoff();\" ><img class=\"rb\" id=\"redbutton\"  alt=\"빨간버튼\" src=\"/food/resources/images/redbutton.png\" width=\"15px\" height=\"15px\"><span class=\"glyphicon rb\"></span>장사 종료</a></li>\r\n");
      out.write("                  <li><a href=\"/food/foodtruckdetail?bId=");
      out.print(((Business)loginMember).getBusiness_Id() );
      out.write("\"><span class=\"glyphicon glyphicon-cutlery\"></span>내 트럭</a></li>\r\n");
      out.write("                  <li><a><span class=\"glyphicon glyphicon-user\"></span> ");
      out.print(((Business)loginMember).getBusiness_Id() );
      out.write("님 </a></li>\r\n");
      out.write("                  <li ><a href=\"/food/views/businessMy/business_my.jsp\"><span class=\"glyphicon glyphicon-th-list\"></span>내 정보 보기</a></li>\r\n");
      out.write("                  <li><a href=\"/food/memberlogout\"><span class=\"glyphicon glyphicon-share\"></span>로그아웃</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               ");
 } else if(loginMember instanceof Manager){
      out.write("\r\n");
      out.write("               <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("               <li><a><span class=\"glyphicon glyphicon-user\"></span> ");
      out.print(((Manager)loginMember).getManager_Id() );
      out.write("님</a></li>\r\n");
      out.write("               <li><a href=\"/food/views/adminMy/admin_my.jsp\"><img alt=\"회원관리\" src=\"/food/resources/images/people.png\" width=\"15px\" height=\"15px\">회원관리</a></li>\r\n");
      out.write("               <li><a href=\"/food/memberlogout\"><span class=\"glyphicon glyphicon-share\"></span>로그아웃</a></li>\r\n");
      out.write("               \r\n");
      out.write("               </ul>\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("         \r\n");
      out.write("      </nav>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- 메인 사진 -->\r\n");
      out.write("\r\n");
      out.write("   <div id=\"mainPhoto\" align=\"center\">\r\n");
      out.write("     \r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"main-t\" align=\"center\">\r\n");
      out.write("      <h3 id=\"mt-h3\">F o o d &nbsp;&nbsp;&nbsp;T r u c k</h3>\r\n");
      out.write("\r\n");
      out.write("      <select id=\"seType\">\r\n");
      out.write("         <option value=\"TRUCK_NAME\">푸드트럭 이름</option>\r\n");
      out.write("         <option value=\"MENU_NAME\">메뉴</option>\r\n");
      out.write("      </select> \r\n");
      out.write("<span style=\"padding:0\">\r\n");
      out.write("      <input  id=\"seValue\" name=\"sevalue\" type=\"search\"  placeholder=\"Search..\" style=\"margin-bottom:0;\"> \r\n");
      out.write("      <a href=\"javascript: getTruckList();\" class=\"glyphicon glyphicon-search\"\r\n");
      out.write("         style=\"text-decoration: none;\"></a> <Br><select style=\"width:162.8px; margin-left:91px; margin-top:0px;\" id=\"autoCompleteSelect\"></select>\r\n");
      out.write("      </span>\r\n");
      out.write("      \r\n");
      out.write("         \r\n");
      out.write("      <br> <br> <br>\r\n");
      out.write("\r\n");
      out.write("      <div style=\"width: 70%; float: left;\">\r\n");
      out.write("      \r\n");
      out.write("         <select id=ctType style=\"margin-right: 50%;\">\r\n");
      out.write("            <option value=\"%\" >전체보기</option>\r\n");
      out.write("            <option value=\"식사류\" >식사류</option>\r\n");
      out.write("            <option value=\"간식류\" >간식류</option>\r\n");
      out.write("            <option value=\"디저트류\" >디저트류</option>\r\n");
      out.write("         </select><br>\r\n");
      out.write("         <br>\r\n");
      out.write("      </div>\r\n");
      out.write("      <table id=\"truck_table\"style=\"width: 70%;\">\r\n");
      out.write("         ");

            int i = 0;
            for (Foodtruck truck : list) {

               if (i % 3 == 0) {
         
      out.write("\r\n");
      out.write("         <tr style=\"border: 1px solid #BDBDBD; padding:10px;\">\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("            <td style=\"border: 1px solid #BDBDBD; width: 30%;  margin:50px; \">\r\n");
      out.write("            <a href=\"foodtruckdetail?bId=");
      out.print(truck.getBusiness_Id());
      out.write("\"><img\r\n");
      out.write("                  src=\"/food/resources/images/foodtruck/");
      out.print(truck.getTruck_Img());
      out.write("\"\r\n");
      out.write("                  style=\"width: 100%; padding: 0px;\"></img></a>\r\n");
      out.write("                 ");
if(truck.getTruck_Live_OnOff().equals("Y")){
      out.write("\r\n");
      out.write("               <h3 style=\"text-align: center\"><img id=\"blink_on\" width=\"20px\" height=\"auto\" src=\"/food/resources/images/btn_on.png\">");
      out.print(truck.getTruck_Name());
      out.write("</h3>\r\n");
      out.write("                  ");
}else{ 
      out.write("\r\n");
      out.write("                  <h3 style=\"text-align: center\">");
      out.print(truck.getTruck_Name());
      out.write("</h3>\r\n");
      out.write("                  ");
} 
      out.write("\r\n");
      out.write("                <h5 style=\"text-align: center ; margin-top: 10px;\">");
      out.print(truck.getTruck_MainMenu());
      out.write("</h5></td>\r\n");
      out.write("               \r\n");
      out.write("            ");

               if (i == (list.size() - 1) || i % 3 == 2) {
            
      out.write("\r\n");
      out.write("         </tr>\r\n");
      out.write("\r\n");
      out.write("         ");

            }
               i++;
            }
         
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("   <!--top3시작 -->\r\n");
      out.write("   \r\n");
      out.write("   <!-- top3끝 -->\r\n");
      out.write("   \r\n");
      out.write("      <!-- div 닫음 -->\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("<span id=\"sidebox\" style=\"width:8%; text-align: center; align:center;\"  > \r\n");
      out.write(" \r\n");
      out.write(" <span style=\"width:120%; align:center; color:#000; font-size:13px\" >금주의 인기트럭  <br>\r\n");
      out.write("<span style=\"color:red\">TOP3</span></span>\r\n");
      out.write(" <br>\r\n");
      out.write(" <div style=\"margin: 10px 0; border-bottom:1px solid #bdbdbd; background-color: red\"></div>\r\n");
      out.write("\r\n");

Foodtruck ftruck = null;
   
   int k=0;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"top3img_div\">\r\n");
      out.write("   ");
 if(riceTop3List!=null){
       cnt =1;
       String sss[]={"식사류 | ","간식류 | ","디저트류 | "};
      for(FoodTop3 ft : riceTop3List){
      out.write("\r\n");
      out.write("   <br>\r\n");
      out.write("   \r\n");
      out.write("   <a id=\"a_tag_top");
      out.print(cnt );
      out.write("\" href=\"foodtruckdetail?bId=");
      out.print(ft.getBusinessId());
      out.write("\">\r\n");
      out.write("   <img id=\"top3img");
      out.print(cnt );
      out.write("\" style=\"width:100%;  margin-bottom: 0px; \"  src=\"/food/resources/images/foodtruck/");
      out.print(ft.getTruckImg());
      out.write("\"></a>\r\n");
      out.write("   <br>\r\n");
      out.write("   <span id=\"nametag_top");
      out.print(cnt );
      out.write("\" style=\"width:110%; vertical-align:center; font-size:13px; text-align: center; margin-top: 0px; color: gray\">");
      out.print(sss[(cnt++)-1]);
      out.write("<strong>");
      out.print(ft.getTruckName() );
      out.write("</strong></span>\r\n");
      out.write("   <br>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   ");
 }}else{
      out.write("\r\n");
      out.write("   ~~~~\r\n");
      out.write("   ");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <br style=\"clear: both\">\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"foot\" style=\"bottom: 0;\">\r\n");
      out.write("      <p>FoodTruck &nbsp;Copyright @ iei.or.kr &nbsp; All Rights\r\n");
      out.write("         Reserved.</p>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
