/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2018-04-20 02:14:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.userMy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.swing.text.AbstractDocument.Content;
import member.model.vo.*;
import review.model.vo.*;
import java.util.*;
import reply.model.vo.*;
import coupon.model.vo.*;

public final class user_005fmy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("reply.model.vo");
    _jspx_imports_packages.add("coupon.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_packages.add("review.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.swing.text.AbstractDocument.Content");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	int reviewPage = 1;
	//로그인 정보 가져오기
	Customer loginMember = null;
	if (session.getAttribute("loginMember") != null) {
		loginMember = (Customer) session.getAttribute("loginMember");

	} else { //로그인 아니라면 index로 강제 소환

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("      location.href =\"/food/index.jsp\";\r\n");
      out.write("   </script>\r\n");

	}
	//tab 정보 가져오기
	if (request.getAttribute("tab") != null) {

      out.write("\r\n");
      out.write("<script> \r\n");
      out.write("var tab = '");
      out.print(request.getAttribute("tab"));
      out.write("';\r\n");
      out.write("</script>\r\n");

	} else {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   var tab = \"tab-1\";\r\n");
      out.write("</script>\r\n");

	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>푸딩 일반사용자</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/top-menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/foot.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/left-menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/left-menu-tab.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/right-menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/modInfo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/review.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/replay.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/user-my.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"/food/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/jquery.scrollzer.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/skel.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/util.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/main.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var sum= 0;\r\n");
      out.write("var reviewPage=1;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function myReviewAjax(page)\r\n");
      out.write("{\r\n");
      out.write("   reviewPage=page;\r\n");
      out.write("   $.ajax({\r\n");
      out.write("      url: \"/food/cusmyreviewlist\",\r\n");
      out.write("      type : \"post\",\r\n");
      out.write("      data : {\r\n");
      out.write("         \"userId\" : '");
      out.print(((Customer) loginMember).getCustomer_Id());
      out.write("',\r\n");
      out.write("         \"page\" : reviewPage ,\r\n");
      out.write("         \"seType\" : $('#reviewSeType').val(),\r\n");
      out.write("         \"seValue\" : $('#reviewSeValue').val()\r\n");
      out.write("      },\r\n");
      out.write("      dataType : \"json\",\r\n");
      out.write("      success : function(data){\r\n");
      out.write("         \r\n");
      out.write("         var jsonStr = JSON.stringify(data);\r\n");
      out.write("         var json = JSON.parse(jsonStr);\r\n");
      out.write("         \r\n");
      out.write("         var tableCode = \"\";\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         for(var i in json.list)\r\n");
      out.write("         {\r\n");
      out.write("            tableCode+='<tr><th style=\"width: 15%;\"><input type=\"checkbox\" name=\"delCheck\" value=\"'+json.list[i].no+'\"></th>';\r\n");
      out.write("            tableCode+='<th>'+json.list[i].no+'</th>';\r\n");
      out.write("            tableCode+='<th><a href=\"/food/reviewdetail?reviewNo='+json.list[i].no+'\">'+json.list[i].title+'</a></th>';\r\n");
      out.write("            tableCode+='<th>'+json.list[i].date+'</th>';\r\n");
      out.write("            tableCode+='<th>'+json.list[i].count+'</th></tr>';\r\n");
      out.write("         }\r\n");
      out.write("         $('#reviewTable').html(tableCode);\r\n");
      out.write("/////////////////////////////////////////////////////////\r\n");
      out.write("         var maxPage = json.maxPage;\r\n");
      out.write("         var startPage = json.startPage;\r\n");
      out.write("         var endPage = json.endPage;\r\n");
      out.write("         reviewPage = json.currentPage;\r\n");
      out.write("         \r\n");
      out.write("         var pageCode = \"\";\r\n");
      out.write("         \r\n");
      out.write("         if (reviewPage <= 1){\r\n");
      out.write("            pageCode+= \"[맨처음]&nbsp\";\r\n");
      out.write("         }else{\r\n");
      out.write("            pageCode+= \"<a href='javascript: myReviewAjax(1);'>[맨처음]</a>\"\r\n");
      out.write("         }\r\n");
      out.write("         if ((reviewPage - 10) < startPage\r\n");
      out.write("               && (reviewPage - 10) >= 1) {\r\n");
      out.write("            pageCode += '<a href=\"javascript:myReviewAjax('\r\n");
      out.write("                  + (startPage - 1) + ');\">[prev]</a>';\r\n");
      out.write("         } else {\r\n");
      out.write("            pageCode += '[prev]&nbsp;';\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         for (var p = startPage; p <= endPage; p++) {\r\n");
      out.write("            if (p == reviewPage) {\r\n");
      out.write("               pageCode += '<font color=\"red\" size=\"4\"><b>[' + p\r\n");
      out.write("                     + ']</b></font>';\r\n");
      out.write("            } else {\r\n");
      out.write("               pageCode += '<a href=\"javascript:myReviewAjax('\r\n");
      out.write("                     + p + ');\">' + p + '</a>';\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         if ((reviewPage + 10) > endPage\r\n");
      out.write("               && (reviewPage + 10) <= maxPage) {\r\n");
      out.write("            pageCode += '<a href=\"javascript:myReviewAjax('\r\n");
      out.write("                  + (endPage + 1) + ')\">[next]</a>';\r\n");
      out.write("\r\n");
      out.write("         } else {\r\n");
      out.write("            pageCode += '[next]&nbsp';\r\n");
      out.write("         }\r\n");
      out.write("         if (reviewPage >= maxPage) {\r\n");
      out.write("            pageCode += '[맨끝]&nbsp';\r\n");
      out.write("         } else {\r\n");
      out.write("            pageCode += '<a href=\"javascript:myReviewAjax('\r\n");
      out.write("                  + maxPage + ')\">[맨끝]</a>';\r\n");
      out.write("         }\r\n");
      out.write("         console.log(pageCode);\r\n");
      out.write("         console.log(\"reviewPage: \"+reviewPage);\r\n");
      out.write("         console.log(\"maxPage: \"+maxPage);\r\n");
      out.write("         console.log(\"endPage: \"+endPage);\r\n");
      out.write("         console.log(\"startPage: \"+startPage);\r\n");
      out.write("         $('#reviewPaging').html(pageCode);\r\n");
      out.write("      },\r\n");
      out.write("      error : function(){\r\n");
      out.write("         alert(\"myReviewAjax 에러\");\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   });\r\n");
      out.write("      \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function checkedCheck(name)\r\n");
      out.write("{\r\n");
      out.write("   var arr=[];\r\n");
      out.write("   var i=0;\r\n");
      out.write("   sum = 0;\r\n");
      out.write("   $('[name='+name+']').each(function(){\r\n");
      out.write("      if( $(this).is(\":checked\")==true )\r\n");
      out.write("         {\r\n");
      out.write("         arr[i]=1;\r\n");
      out.write("         }\r\n");
      out.write("      else{\r\n");
      out.write("         arr[i]=0;\r\n");
      out.write("      }\r\n");
      out.write("      i++;\r\n");
      out.write("      \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   for(var j=0; j< arr.length; j++)\r\n");
      out.write("      {\r\n");
      out.write("      sum+=arr[j];\r\n");
      out.write("      }\r\n");
      out.write("   return sum;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("   $(function() {\r\n");
      out.write("\r\n");
      out.write("      $('#delBtn').click(function(){\r\n");
      out.write("         if( checkedCheck('delCheck') >0  ){\r\n");
      out.write("            $('#delSubmit').click();\r\n");
      out.write("         }else\r\n");
      out.write("            {\r\n");
      out.write("            alert(\"선택된 항이 없습니다\");\r\n");
      out.write("            }\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $('#delBtn2').click(function(){\r\n");
      out.write("         if(checkedCheck('reply_check') >0){\r\n");
      out.write("            $('#delSubmit2').click();\r\n");
      out.write("         }else{\r\n");
      out.write("            alert(\"선택된 항이 없습니다.\");\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      if (tab != null) {\r\n");
      out.write("         $('.tab-content').removeClass('current');\r\n");
      out.write("         $('.tabs li').removeClass('current');\r\n");
      out.write("         $('.tabs li a').removeClass('active');\r\n");
      out.write("         $('#' + tab).addClass(' current');\r\n");
      out.write("         $('[data-tab='+tab+'] a').addClass('active');\r\n");
      out.write("         console.log('[data-tab='+tab+']');\r\n");
      out.write("         tab=null;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      $('.tabs li').click(function() {\r\n");
      out.write("         var tab_cl = $(this).attr('data-tab');\r\n");
      out.write("\r\n");
      out.write("         $('.tabs li').removeClass('current');\r\n");
      out.write("         $('.tab-content').removeClass('current');\r\n");
      out.write("         $(this).addClass('current');\r\n");
      out.write("         $(\".\" + tab_cl).addClass('current');\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $('#delCheck').change(function(){\r\n");
      out.write("         //리뷰 전체선택 체크박스 선택\r\n");
      out.write("      if(   $('#delCheck').is(\":checked\")==true )\r\n");
      out.write("         {\r\n");
      out.write("            $('[name=delCheck]').attr(\"checked\",true);\r\n");
      out.write("         }\r\n");
      out.write("      else if ( $('#delCheck').is(\":checked\")==false )\r\n");
      out.write("         {\r\n");
      out.write("         $('[name=delCheck]').attr(\"checked\",false);\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $('#reply_all_check').change(function(){\r\n");
      out.write("      //댓글 전체선택 체크박스 선택\r\n");
      out.write("         if( $('#reply_all_check').is(\":checked\")==true ){\r\n");
      out.write("            \r\n");
      out.write("            $('[name=reply_check]').attr(\"checked\",true);\r\n");
      out.write("            }\r\n");
      out.write("         else if ($('#reply_add_check').is(\":checked\")==false)\r\n");
      out.write("         {\r\n");
      out.write("            $('[name=reply_check]').attr(\"checked\",false);\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   //한결이오빠코드\r\n");
      out.write("   function csmodify() {\r\n");
      out.write("      if (opwCheck == 0) {\r\n");
      out.write("         if (cpwCheck == 0 && vcodeCheck == 0) {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("               url : \"/food/mupdate.pwenc\",\r\n");
      out.write("               data : {\r\n");
      out.write("                  userName :$('#userName').val() ,\r\n");
      out.write("                  withdraw : $('#withdraw').val() ,\r\n");
      out.write("                  userId : $('#ID').val(),\r\n");
      out.write("                  userPwd : $('#newPasswordRepeat').val(),\r\n");
      out.write("                  email : $('#email2').val()\r\n");
      out.write("               },\r\n");
      out.write("               type : \"post\",\r\n");
      out.write("               success : function(data) {\r\n");
      out.write("                  $('#newPassword').text(\"\");\r\n");
      out.write("                  $('#newPasswordRepeat').text(\"\");\r\n");
      out.write("                  $('#codeinput').css('display', 'none');\r\n");
      out.write("                  $('#numbersend').text('인증번호 발송');\r\n");
      out.write("                  $('#email2').text(\"\");\r\n");
      out.write("                  location.href = \"/food/views/userMy/user_my.jsp\";\r\n");
      out.write("                  alert('회원정보 수정 완료!');\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("         } else if (cpwCheck == 0 && vcodeCheck != 0\r\n");
      out.write("               && $('#newPasswordRepeat').val() != \"\") {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("               url : \"/food/mupdate.pwenc\",\r\n");
      out.write("               data : {\r\n");
      out.write("                  userId : $('#ID').val(),\r\n");
      out.write("                  userPwd : $('#newPasswordRepeat').val(),\r\n");
      out.write("                  email : $('#email').val()\r\n");
      out.write("               },\r\n");
      out.write("               type : \"post\",\r\n");
      out.write("               success : function(data) {\r\n");
      out.write("                  $('#newPassword').text(\"\");\r\n");
      out.write("                  $('#newPasswordRepeat').text(\"\");\r\n");
      out.write("                  $('#email2').text(\"\");\r\n");
      out.write("                  location.href = \"/food/views/userMy/user_my.jsp\";\r\n");
      out.write("                  alert('회원정보 수정 완료!');\r\n");
      out.write("               }\r\n");
      out.write("               });\r\n");
      out.write("         } else if (cpwCheck != 0 && vcodeCheck == 0) {\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("               url : \"/food/mupdate.pwenc\",\r\n");
      out.write("               data : {\r\n");
      out.write("                  userId : $('#ID').val(),\r\n");
      out.write("                  userPwd : $('#oldPassword').val(),\r\n");
      out.write("                  email : $('#email2').val()\r\n");
      out.write("               },\r\n");
      out.write("               type : \"post\",\r\n");
      out.write("               success : function(data) {\r\n");
      out.write("                  $('#newPassword').text(\"\");\r\n");
      out.write("                  $('#newPasswordRepeat').text(\"\");\r\n");
      out.write("                  $('#codeinput').css('display', 'none');\r\n");
      out.write("                  $('#numbersend').text('인증번호 발송');\r\n");
      out.write("                  $('#email2').text(\"\");\r\n");
      out.write("                  location.href = \"/food/views/userMy/user_my.jsp\";\r\n");
      out.write("                  alert('회원정보 수정완료!');\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("         } else {\r\n");
      out.write("            alert(\"입력하신 정보가 없습니다.\");\r\n");
      out.write("         }\r\n");
      out.write("      } else {\r\n");
      out.write("         alert(\"현재 비밀번호를 입력해주세요.\");\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   var vcodeCheck = 1;\r\n");
      out.write("   var opwCheck = 1;\r\n");
      out.write("   var cpwCheck = 1;\r\n");
      out.write("   var vcode = null;\r\n");
      out.write("   function checkMail() {\r\n");
      out.write("      if ($('#email2').val() != null) {\r\n");
      out.write("         if ($('#codeinput').css('display') == 'block'\r\n");
      out.write("               || $('#numbersend').text() == '인증번호 재발송') {\r\n");
      out.write("            $('#codeinput').css('display', 'none');\r\n");
      out.write("            $('#numbersend').text('인증번호 발송');\r\n");
      out.write("         }\r\n");
      out.write("         var email = $(\"#email2\").val();\r\n");
      out.write("\r\n");
      out.write("         var exptext = /^[A-Za-z0-9_\\.\\-]+@[A-Za-zS0-9\\-]+\\.[A-Za-z0-9\\-]+/;\r\n");
      out.write("         if ($('#email2').val() == \"\") {\r\n");
      out.write("            alert(\"입력하신 이메일이 없습니다.\");\r\n");
      out.write("         } else if (exptext.test(email) == false) {\r\n");
      out.write("            if ($('#codeinput').css('display') == 'block'\r\n");
      out.write("                  || $('#numbersend').text() == '인증번호 재발송') {\r\n");
      out.write("               $('#codeinput').css('display', 'none');\r\n");
      out.write("               $('#numbersend').text('인증번호 발송');\r\n");
      out.write("            }\r\n");
      out.write("            //이메일 형식이 알파벳+숫자@알파벳+숫자.알파벳+숫자 형식이 아닐경우         \r\n");
      out.write("            alert(\"이메일형식이 올바르지 않습니다.\");\r\n");
      out.write("            $('#email2').focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         } else {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("               url : \"/food/checkmail\",\r\n");
      out.write("               data : {\r\n");
      out.write("                  userId : $('#ID').val(),\r\n");
      out.write("                  email : $('#email2').val()\r\n");
      out.write("               },\r\n");
      out.write("               type : \"post\",\r\n");
      out.write("               success : function(data) {\r\n");
      out.write("                  if (data == 0) {\r\n");
      out.write("                     if ($('#codeinput').css('display') == 'block'\r\n");
      out.write("                           || $('#numbersend').text() == '인증번호 재발송') {\r\n");
      out.write("                        $('#codeinput').css('display', 'none');\r\n");
      out.write("                        $('#numbersend').text('인증번호 발송');\r\n");
      out.write("                     }\r\n");
      out.write("                     alert(\"중복되는 이메일 입니다.\");\r\n");
      out.write("                  } else if (data == 1) {\r\n");
      out.write("                     $('#numbersend').text(\"인증번호 재발송\");\r\n");
      out.write("                     $('#codeinput').css('display', 'block');\r\n");
      out.write("                     $.ajax({\r\n");
      out.write("                        url : \"/food/sendmail\",\r\n");
      out.write("                        data : {\r\n");
      out.write("                           email : $('#email2').val()\r\n");
      out.write("                        },\r\n");
      out.write("                        type : \"post\",\r\n");
      out.write("                        success : function(data) {\r\n");
      out.write("                           vcode = Number(data);\r\n");
      out.write("                           console.log(vcode);\r\n");
      out.write("                           alert(\"인증번호를 전송하였습니다.\");\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                  }\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   function vCodeCheck() {\r\n");
      out.write("      //이메일 인증버튼 클릭하면 실행되는 함수\r\n");
      out.write("      //이메일 인증번호와 서버의 인증번호를 비교하여\r\n");
      out.write("      //맞으면 checkVCode=true\r\n");
      out.write("      //틀리면 checkVCode=false\r\n");
      out.write("\r\n");
      out.write("      if (vcode == $('#vCode').val()) {\r\n");
      out.write("         alert('인증완료');\r\n");
      out.write("         vcodeCheck = 0;\r\n");
      out.write("      } else {\r\n");
      out.write("         alert('인증번호를 확인해주세요~ ^~!');\r\n");
      out.write("         vcodeCheck = 1;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("   function checkPwd() {\r\n");
      out.write("      //비밀번호 확인\r\n");
      out.write("      if ($('#newPassword').val() != $('#newPasswordRepeat').val()) {\r\n");
      out.write("         alert('암호와 암호확인 값이 일치하지 않습니다.\\n' + '다시 입력하십시오.');\r\n");
      out.write("         $('#newPasswordRepeat').val(\"\");\r\n");
      out.write("         cpwCheck = 1;\r\n");
      out.write("      } else {\r\n");
      out.write("         cpwCheck = 0;\r\n");
      out.write("      }\r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("   function checkPwd2() {\r\n");
      out.write("      //비밀번호 확인\r\n");
      out.write("      var regExp = /[\\{\\}\\[\\]\\/?.,;:|\\)*~`!^\\-_+<>@#$%&\\\\\\=\\(\\'\\\"\\s]/gi;\r\n");
      out.write("      if ($('#oldPassword').val() != null && $('#newPassword').val()) {\r\n");
      out.write("         if ($('#oldPassword').val() == $('#newPassword').val()) {\r\n");
      out.write("            alert('현재 비밀번호와 새 비밀번호가 같습니다.\\n' + '새 비밀번호를 다시 입력하십시오.');\r\n");
      out.write("            $('#newPassword').val(\"\");\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("      if (regExp.test($('#newPassword').val())) {\r\n");
      out.write("         alert(\"특수문자를 쓰실수없습니다.\");\r\n");
      out.write("         var m = $('#newPassword').val().replace(regExp, \"\");\r\n");
      out.write("         $('#newPassword').val(\"\");\r\n");
      out.write("         $('#newPassword').focus();\r\n");
      out.write("      }\r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function withdraw() {\r\n");
      out.write("      if (opwCheck == 0) {\r\n");
      out.write("         var answer = confirm(\"정말 탈퇴 하시겠습니까 ? \");\r\n");
      out.write("\r\n");
      out.write("         if (answer) {\r\n");
      out.write("            var writer = prompt(\"\\\"탈퇴\\\"라고 적어주세요.\");\r\n");
      out.write("            if (writer == \"탈퇴\") {\r\n");
      out.write("               $.ajax({\r\n");
      out.write("                  url : \"/food/withdraw\",\r\n");
      out.write("                  data : {\r\n");
      out.write("                     ID : $('#ID').val(),\r\n");
      out.write("                  },\r\n");
      out.write("                  type : \"post\",\r\n");
      out.write("                  success : function(data) {\r\n");
      out.write("                     if (data == 1) {\r\n");
      out.write("                        alert('탈퇴 성공!');\r\n");
      out.write("                        location.reload();\r\n");
      out.write("                     } else {\r\n");
      out.write("                     }\r\n");
      out.write("                  }\r\n");
      out.write("               });\r\n");
      out.write("            }\r\n");
      out.write("         } else {\r\n");
      out.write("         }\r\n");
      out.write("      } else {\r\n");
      out.write("         alert(\"현재 비밀번호를 입력해주세요.\");\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("function checkOldPwd() {\r\n");
      out.write("   //현재 비밀번호 확인\r\n");
      out.write("   if ($('#oldPassword').val() != null\r\n");
      out.write("         && $('#oldPassword').val().length > 0) {\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url : \"/food/checkcspwd.pwenc\",\r\n");
      out.write("         type : \"post\",\r\n");
      out.write("         data : {\r\n");
      out.write("            \"userPwd\" : $('#oldPassword').val(),\r\n");
      out.write("            \"userId\" : $('#ID').val()\r\n");
      out.write("         },\r\n");
      out.write("         success : function(data) {\r\n");
      out.write("            if (data == 0) {\r\n");
      out.write("               alert('현재 비밀번호가 일치하지 않습니다.');\r\n");
      out.write("               $('#oldPassword').val('');\r\n");
      out.write("               opwCheck = 1;\r\n");
      out.write("            } else if (data == 1) {\r\n");
      out.write("               opwCheck = 0;\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".mod_table {\r\n");
      out.write("\tbackground-color: #DCDCDC;\r\n");
      out.write("\tborder-color: black;\r\n");
      out.write("\twidth: 170px;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\" style=\"top: 50px\">\r\n");
      out.write("\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t<ul id=\"ul\" class=\"tabs\">\r\n");
      out.write("\t\t\t\t<li class=\"current\" data-tab=\"tab-1\"><a href=\"#edit\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon fa-edit\">회원정보수정</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-2\"><a href=\"/food/csreview\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon fa-user\">내후기보기</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-3\"><a href=\"/food/csreplylist\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon fa-user\">내댓글보기</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-4\"><a href=\"/food/clist\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon fa-envelope\">쿠폰확인</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-5\"><a href=\"/food/cusedlist\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon fa-envelope-o\">쿠폰사용내역</span></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"navcl\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\"\r\n");
      out.write("\t\t\t\tstyle=\"padding-left: 0px;\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li style=\"margin-right: 10px;\"><a class=\"navbar-brand\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/food/index.jsp \"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"/food/resources/images/LOGO_fooding.png\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 65px; height: 30px;\">\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/slocation\">지역검색</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/flist\">푸드트럭</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/fes_show\">축제검색</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					if (loginMember == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/views/logIn/logIn.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/views/signUp/select_signUp.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-edit\"></span> 회원가입</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					} else if (loginMember instanceof Customer) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a><span class=\"glyphicon glyphicon-user\"></span> ");
      out.print(((Customer) loginMember).getCustomer_Id());
      out.write("님</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"/food/views/userMy/user_my.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-th-list\"></span>내 정보 보기</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/memberlogout\"><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-share\"></span>로그아웃</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 회원정보 수정 코드 부분~~~ -->\r\n");
      out.write("\t<div id=\"tab-1\" class=\"tab-content tab-1 \" style=\"margin-bottom: 0px\">\r\n");
      out.write("\t\t<div id=\"tab-1div\">\r\n");
      out.write("\t\t\t<!-- <form id=\"frm\" method=\"post\" action=\"/food/bupdate.pwenc\"> -->\r\n");
      out.write("\t\t\t<div class=\"input-group\"\r\n");
      out.write("\t\t\t\tstyle=\"margin-left: 250px; margin-top: 45px;\">\r\n");
      out.write("\t\t\t\t<h3>회원정보 수정</h3>\r\n");
      out.write("\t\t\t\t<div style=\"border-bottom: 1px solid #bdbdbd; width: 500px;\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"width: 500px; margin-left: 250px;\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(((Customer) loginMember).getCustomer_Name());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tid=\"userName\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(((Customer) loginMember).getWithdraw());
      out.write("\" id=\"withdraw\">\r\n");
      out.write("\t\t\t\t\t<input id=\"ID\" type=\"text\" class=\"form-control\" name=\"ID\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"아이디\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(((Customer) loginMember).getCustomer_Id());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<input id=\"oldPassword\" type=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tname=\"oldPassword\" placeholder=\"현재 비밀번호\" style=\"margin-top: 10px;\"\r\n");
      out.write("\t\t\t\t\t\tonblur=\"checkOldPwd();\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<input id=\"newPassword\" type=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tname=\"newPassword\" placeholder=\"새 비밀번호\" style=\"margin-top: 10px;\"\r\n");
      out.write("\t\t\t\t\t\tonblur=\"checkPwd2();\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<input id=\"newPasswordRepeat\" type=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tname=\"newPasswordRepeat\" placeholder=\"새 비밀번호 확인\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-top: 10px;\" onblur=\"checkPwd();\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<input id=\"email\" type=\"text\" class=\"form-control\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Email\" style=\"margin-top: 10px;\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(((Customer) loginMember).getCustomer_Email());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<input id=\"email2\" type=\"email\" class=\"form-control\" name=\"email2\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"new Email\" style=\"margin-top: 10px;\" required>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<button id=\"numbersend\" class=\"btn btn-outline-primary\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-top: 10px;\" onclick=\"checkMail();\">인증번호 발송</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"codeinput\" class=\"input-group\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<input id=\"vCode\" type=\"text\" class=\"form-control\" name=\"vCode\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"인증번호 입력\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-outline-primary\" style=\"margin-top: 10px;\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"vCodeCheck();\">확인</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"input-group\" style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t\t<span><button class=\"btn btn-outline-primary\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-right: 200px\" onclick=\"csmodify();\">수정하기</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-outline-primary\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"position: absolute; margin-left: -80px\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"withdraw();\">탈퇴하기</button> </span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br> <br> <br>\r\n");
      out.write("\t\t\t<!-- </form> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 내 후기보기 코드 부분~~~~~ -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tab-2\" class=\"tab-content tab-2\"\r\n");
      out.write("\t\tstyle=\"margin: 0px; margin-left: 250px\">\r\n");
      out.write("\t\t<div class=\"container\"\r\n");
      out.write("\t\t\tstyle=\"margin-left: 15%; margin-right: 15%; margin-top: 3%;\">\r\n");
      out.write("\t\t\t<h3>내후기 보기</h3>\r\n");
      out.write("\t\t\t<div style=\"border-bottom: 1px solid #bdbdbd;\"></div>\r\n");
      out.write("\t\t\t<br> <select name=\"seType\" id=\"reviewSeType\">\r\n");
      out.write("\t\t\t\t<option value=\"REVIEW_TITLE\" selected>제목만\r\n");
      out.write("\t\t\t\t<option value=\"REVIEW_CONTENT\">내용만\r\n");
      out.write("\t\t\t\t<option value=\"REVIEW_NO\">글번호\r\n");
      out.write("\t\t\t</select> <input type=\"text\" name=\"seValue\" id=\"reviewSeValue\">&nbsp;\r\n");
      out.write("\t\t\t<input type=\"button\" onclick=\"myReviewAjax(1);\" value=\"검색\"\r\n");
      out.write("\t\t\t\tstyle=\"background: green; border: green; color: white;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"csreviewdel\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width: 15%;\"><input id=\"delCheck\" type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"delCheckAll\" value=null>전체선택</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>글번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"reviewTable\">\r\n");
      out.write("\t\t\t\t\t\t");

							int listCount = 0;
							int startPage = 0;
							int endPage = 0;
							int maxPage = 0;
							int currentPage = 0;
							if (request.getAttribute("review_list") != null) {
								ArrayList<Review> reviewList = (ArrayList<Review>) request.getAttribute("review_list");
								listCount = ((Integer) request.getAttribute("listCount")).intValue();
								startPage = ((Integer) request.getAttribute("startPage")).intValue();
								endPage = ((Integer) request.getAttribute("endPage")).intValue();
								maxPage = ((Integer) request.getAttribute("maxPage")).intValue();
								currentPage = ((Integer) request.getAttribute("currentPage")).intValue();

								for (Review review : reviewList) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width: 15%;\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"delCheck\" value=\"");
      out.print(review.getNumber());
      out.write("\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(review.getNumber());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/food/reviewdetail?reviewNo=");
      out.print(review.getNumber());
      out.write('"');
      out.write('>');
      out.print(review.getReview_title());
      out.write("</a></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(review.getReview_Date());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(review.getReview_Count());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

							}
							} else {
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th><font color=\"gray\">후기 없음</font></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<hr style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" hidden id=\"delSubmit\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"button\" value=\"삭제하기\" id=\"delBtn\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div style=\"text-align: center;\" id=\"reviewPaging\">\r\n");
      out.write("\t\t\t\t");

					if (currentPage <= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨처음]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"javascript:myReviewAjax(1);\">[맨처음]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage - 10) < startPage && (currentPage - 10) >= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"javascript:myReviewAjax(");
      out.print(startPage - 1);
      out.write(");\">[prev]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[prev]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 현재 페이지가 포함된 그룹의 페이지 숫자 출력 -->\r\n");
      out.write("\t\t\t\t");

					for (int p = startPage; p <= endPage; p++) {
						if (p == currentPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<font color=\"red\" size=\"4\"><b>[");
      out.print(p);
      out.write("]\r\n");
      out.write("\t\t\t\t</b></font>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"javascript:myReviewAjax(");
      out.print(p);
      out.write(");\">");
      out.print(p);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage + 10) > endPage && (currentPage + 10) <= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"javascript:myReviewAjax(");
      out.print(endPage + 1);
      out.write(");\">[next]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[next]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (currentPage >= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨끝]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"javascript:myReviewAjax(");
      out.print(maxPage);
      out.write(");\">[맨끝]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- <input type=\"button\" value=\"테스트\" onclick=\"myReviewAjax(1);\"> -->\r\n");
      out.write("\t\t\t\t<br style=\"margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t<form style=\"float: right;\" action=\"/food/cssearchreview\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\"></form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br> <br> <br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 내 댓글보기 코드 부분~~~~ -->\r\n");
      out.write("\t<div id=\"tab-3\" class=\"tab-content tab-3\"\r\n");
      out.write("\t\tstyle=\"margin: 0px; margin-left: 250px\">\r\n");
      out.write("\t\t<div class=\"container\"\r\n");
      out.write("\t\t\tstyle=\"margin-left: 15%; margin-right: 15%; margin-top: 3%;\">\r\n");
      out.write("\t\t\t<h3>내댓글 보기</h3>\r\n");
      out.write("\t\t\t<div style=\"border-bottom: 1px solid #bdbdbd;\"></div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"csreplydel\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width: 10%; min-width: 100px;\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"checkbox\" id=\"reply_all_check\">전체선택</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if (request.getAttribute("reply_list") != null) {
								ArrayList<Reply> replyList = (ArrayList<Reply>) request.getAttribute("reply_list");
								listCount = ((Integer) request.getAttribute("listCount")).intValue();
								startPage = ((Integer) request.getAttribute("startPage")).intValue();
								endPage = ((Integer) request.getAttribute("endPage")).intValue();
								maxPage = ((Integer) request.getAttribute("maxPage")).intValue();
								currentPage = ((Integer) request.getAttribute("currentPage")).intValue();

								for (Reply reply : replyList) {
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><input type=\"checkbox\" name=\"reply_check\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(reply.getReply_No());
      out.write("\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(reply.getReply_Content());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"reviewdetail?reviewNo=");
      out.print(reply.getReview_No());
      out.write("\">원문보기</a></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(reply.getReply_Date());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

							}
							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th><font color=\"gray\">댓글 없음</font></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<hr style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"삭제하기\" id=\"delBtn2\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"submit\" hidden id=\"delSubmit2\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t");

					if (currentPage <= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨처음]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/csreplylist?page\">[맨처음]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage - 10) < startPage && (currentPage - 10) >= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/csreplylist?page=");
      out.print(startPage - 1);
      out.write("\">[prev]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[prev]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 현재 페이지가 포함된 그룹의 페이지 숫자 출력 -->\r\n");
      out.write("\t\t\t\t");

					for (int p = startPage; p <= endPage; p++) {
						if (p == currentPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<font color=\"red\" size=\"4\"><b>[");
      out.print(p);
      out.write("]\r\n");
      out.write("\t\t\t\t</b></font>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/csreplylist?page=");
      out.print(p);
      out.write('"');
      out.write('>');
      out.print(p);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage + 10) > endPage && (currentPage + 10) <= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/csreplylist?page=");
      out.print(endPage + 1);
      out.write("\">[next]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[next]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (currentPage >= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨끝]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/csreplylist?page=");
      out.print(maxPage);
      out.write("\">[맨끝]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<br> <br> <br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"tab-4\" class=\"tab-content tab-4\"\r\n");
      out.write("\t\tstyle=\"margin: 0px; margin-left: 250px\">\r\n");
      out.write("\t\t<div class=\"container\"\r\n");
      out.write("\t\t\tstyle=\"margin-left: 15%; margin-right: 15%; margin-top: 2%;\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<form action=\"/food/cserachFoodtruck\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><h3>쿠폰 확인</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"border-bottom: 1px solid #bdbdbd; width: 1145px;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-top: 5px; position: absolute; right: 20%;\"><input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" name=\"cSearchFoodtrcuk\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"가게명 검색\" style=\"width-min: 130px;\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-top: 15px; position: absolute; right: 16%;\"><input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\" class=\"btn btn-outline-primary;\" value=\"검색\">\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"width: 10%; min-width: 100px;\">가게명</th>\r\n");
      out.write("\t\t\t\t\t\t<th>쿠폰</th>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"width: 12%; min-width: 100px;\">사용기한</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody style=\"text-align: center; vertical-align: middle;\">\r\n");
      out.write("\t\t\t\t\t");

						listCount = 1;
						startPage = 1;
						endPage = 1;
						maxPage = 1;
						currentPage = 1;
						if (request.getAttribute("coupon_list") != null) { //쿠폰리스트 요청이 널이 아니라면
							ArrayList<Coupon_l> couponList = (ArrayList<Coupon_l>) request.getAttribute("coupon_list");
							//쿠폰리스트를 어레이리스트에 담고
							listCount = ((Integer) request.getAttribute("listCount")).intValue();
							startPage = ((Integer) request.getAttribute("startPage")).intValue();
							endPage = ((Integer) request.getAttribute("endPage")).intValue();
							maxPage = ((Integer) request.getAttribute("maxPage")).intValue();
							currentPage = ((Integer) request.getAttribute("currentPage")).intValue();

							for (Coupon_l c : couponList) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(c.getTruck_name());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(c.getCoupon_content());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(c.getCoupon_date());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						}
						} else {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td><font color=\"gray\">");
      out.print(request.getAttribute("couponMessage"));
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<hr style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t");

					if (currentPage <= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨처음]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/clist?currentPage=1\">[맨처음]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage - 10) < startPage && (currentPage - 10) >= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/clist?currentPage=");
      out.print(startPage - 1);
      out.write("\">[prev]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[prev]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 현재 페이지가 포함된 그룹의 페이지 숫자 출력 -->\r\n");
      out.write("\t\t\t\t");

					for (int p = startPage; p <= endPage; p++) {
						if (p == currentPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<font color=\"red\" size=\"4\"><b>[");
      out.print(p);
      out.write("]\r\n");
      out.write("\t\t\t\t</b></font>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/clist?currentPage=");
      out.print(p);
      out.write('"');
      out.write('>');
      out.print(p);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage + 10) > endPage && (currentPage + 10) <= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/clist?currentPage=");
      out.print(endPage + 1);
      out.write("\">[next]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[next]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (currentPage >= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨끝]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/clist?currentPage=");
      out.print(maxPage);
      out.write("\">[맨끝]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br> <br> <br>\r\n");
      out.write("\t\t<!-- tab-4 끝나는 div -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"tab-5\" class=\"tab-content tab-5\"\r\n");
      out.write("\t\tstyle=\"margin: 0px; margin-left: 250px\">\r\n");
      out.write("\t\t<div class=\"container\"\r\n");
      out.write("\t\t\tstyle=\"margin-left: 8.5%; margin-right: 15%; margin-top: 3.2%;\">\r\n");
      out.write("\t\t\t<div class=\"container\"\r\n");
      out.write("\t\t\t\tstyle=\"margin-left: 8.5%; margin-right: 15%; margin-top: 3.2%;\">\r\n");
      out.write("\t\t\t\t<h3>쿠폰 사용 내역</h3>\r\n");
      out.write("\t\t\t\t<div style=\"border-bottom: 1px solid #bdbdbd; width: 1145px\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table class=\"table table-striped\" style=\"width: 1145px;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width: 10%; min-width: 100px;\">가게명</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>쿠폰</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width: 15%; min-width: 100px;\">사용날짜</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody style=\"text-align: center; vertical-align: middle;\">\r\n");
      out.write("\t\t\t\t\t\t");

							listCount = 0;
							startPage = 0;
							endPage = 0;
							maxPage = 0;
							currentPage = 0;
							if (request.getAttribute("coupon_list") != null) { //쿠폰리스트 요청이 널이 아니라면
								ArrayList<Coupon_l> couponList = (ArrayList<Coupon_l>) request.getAttribute("coupon_list");
								//쿠폰리스트를 어레이리스트에 담고
								listCount = ((Integer) request.getAttribute("listCount")).intValue();
								startPage = ((Integer) request.getAttribute("startPage")).intValue();
								endPage = ((Integer) request.getAttribute("endPage")).intValue();
								maxPage = ((Integer) request.getAttribute("maxPage")).intValue();
								currentPage = ((Integer) request.getAttribute("currentPage")).intValue();

								for (Coupon_l c : couponList) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(c.getTruck_name());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(c.getCoupon_content());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(c.getCoupon_date());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

							}
							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font color=\"gray\">");
      out.print(request.getAttribute("couponMessage"));
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<hr style=\"margin-top: 30px; width: 1145px;\">\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center; margin-left: 130px;\">\r\n");
      out.write("\t\t\t\t\t");

						if (currentPage <= 1) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t[맨처음]&nbsp;\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/food/cusedlist?currentPage=1\">[맨처음]</a>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						if ((currentPage - 10) < startPage && (currentPage - 10) >= 1) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/food/cusedlist?currentPage=");
      out.print(startPage - 1);
      out.write("\">[prev]</a>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t[prev]&nbsp;\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 현재 페이지가 포함된 그룹의 페이지 숫자 출력 -->\r\n");
      out.write("\t\t\t\t\t");

						for (int p = startPage; p <= endPage; p++) {
							if (p == currentPage) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<font color=\"red\" size=\"4\"><b>[");
      out.print(p);
      out.write("]\r\n");
      out.write("\t\t\t\t\t</b></font>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/food/cusedlist?currentPage=");
      out.print(p);
      out.write('"');
      out.write('>');
      out.print(p);
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t");

						}
						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						if ((currentPage + 10) > endPage && (currentPage + 10) <= maxPage) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/food/cusedlist?currentPage=");
      out.print(endPage + 1);
      out.write("\">[next]</a>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t[next]&nbsp;\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						if (currentPage >= maxPage) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t[맨끝]&nbsp;\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/food/cusedlist?currentPage=");
      out.print(maxPage);
      out.write("\">[맨끝]</a>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br> <br> <br>\r\n");
      out.write("\t\t<!-- tab-5끝나는 div -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"foot\" style=\"bottom: 0; position: fixed;\">FoodTruck\r\n");
      out.write("\t\t&nbsp;Copyright @ iei.or.kr &nbsp; All Rights Reserved.</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
