/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-04-08 12:41:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class calTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>reservation_1</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css\" />\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.8.3.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/ui/1.10.0/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/demos/style.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("   \r\n");
      out.write("   $('#catype_select').change(function(){\r\n");
      out.write("      //alert($('#catype_select').val());\r\n");
      out.write("      \r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url: \"/cs/carcategory.do\",\r\n");
      out.write("         data: {no: $('#catype_select').val()},\r\n");
      out.write("         type: \"post\",\r\n");
      out.write("         dataType: \"json\",\r\n");
      out.write("         success : function(data){\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function() { \r\n");
      out.write("     $(\"#datepicker1\").datepicker({\r\n");
      out.write("      dateFormat: 'yy'+'년'+'mm'+'월'+'dd'+'일',\r\n");
      out.write("      monthNamesShort: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("        dayNamesMin: ['일','월','화','수','목','금','토'],\r\n");
      out.write("       changeMonth: true, //월변경가능\r\n");
      out.write("        changeYear: true, //년변경가능\r\n");
      out.write("       showMonthAfterYear: true, //년 뒤에 월 표시\r\n");
      out.write("     });\r\n");
      out.write("    });\r\n");
      out.write("$(function() { \r\n");
      out.write("     $(\"#datepicker2\").datepicker({\r\n");
      out.write("      dateFormat: 'yy'+'년'+'mm'+'월'+'dd'+'일',\r\n");
      out.write("      monthNamesShort: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("        dayNamesMin: ['일','월','화','수','목','금','토'],\r\n");
      out.write("       changeMonth: true, //월변경가능\r\n");
      out.write("        changeYear: true, //년변경가능\r\n");
      out.write("       showMonthAfterYear: true, //년 뒤에 월 표시\r\n");
      out.write("     });\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" /* $(function(){\r\n");
      out.write("      $('#catype_select').change(function(){\r\n");
      out.write("         \r\n");
      out.write("          $('#catype_select').val(); \r\n");
      out.write("         \r\n");
      out.write("         $.ajax({\r\n");
      out.write("            url: \"carcategory.do\",\r\n");
      out.write("            data: {no: $('#catype_select').val()},\r\n");
      out.write("            type: \"get\",\r\n");
      out.write("            dataType: \"json\",\r\n");
      out.write("            success: function(data){\r\n");
      out.write("               $('#p4').html($('#p4').text()+\"<br>\"+\r\n");
      out.write("                     data.userid+\",\"+data.userpwd+\",\"+\r\n");
      out.write("                     decodeURIComponent(data.username)\r\n");
      out.write("                     +\",\"+data.age+\",\"+\r\n");
      out.write("                     data.email+\",\"+\r\n");
      out.write("                     data.phone);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("      });\r\n");
      out.write("       \r\n");
      out.write("    });  */\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* Remove the navbar's default margin-bottom and rounded borders */\r\n");
      out.write(".navbar {\r\n");
      out.write("   margin-bottom: 0;\r\n");
      out.write("   border-radius: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set height of the grid so .sidenav can be 100% (adjust as needed) */\r\n");
      out.write(".row.content {\r\n");
      out.write("   height: 450px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set gray background color and 100% height */\r\n");
      out.write(".sidenav {\r\n");
      out.write("   padding-top: 20px;\r\n");
      out.write("   background-color: #f1f1f1;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set black background color, white text and some padding */\r\n");
      out.write("footer {\r\n");
      out.write("   background-color: #555;\r\n");
      out.write("   color: white;\r\n");
      out.write("   padding: 15px;\r\n");
      out.write("   margin-top: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menu {\r\n");
      out.write("   height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#utilMenu>ul {\r\n");
      out.write("   text-align: right;\r\n");
      out.write("   margin-left: 900px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#utilMenu>ul li {\r\n");
      out.write("   list-style: none;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#utilMenu>ul li a {\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   margin-right: 10px;\r\n");
      out.write("   font-size: 8pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-inner img {\r\n");
      out.write("   -webkit-filter: grayscale(90%);\r\n");
      out.write("   filter: grayscale(90%); /* make all photos black and white */\r\n");
      out.write("   width: 100%; /* Set width to 100% */\r\n");
      out.write("   margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption h3 {\r\n");
      out.write("   color: #fff !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#imageslide {\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 600px) {\r\n");
      out.write("   .carousel-caption {\r\n");
      out.write("      display: none;\r\n");
      out.write("      /* Hide the carousel text when the screen is less than 600 pixels wide */\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* On small screens, set height to 'auto' for sidenav and grid */\r\n");
      out.write("@media screen and (max-width: 767px) {\r\n");
      out.write("   .sidenav {\r\n");
      out.write("      height: auto;\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("   }\r\n");
      out.write("   .row.content {\r\n");
      out.write("      height: auto;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <!-- <nav class=\"navbar navbar-inverse\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("         <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("               data-target=\"#myNavbar\">\r\n");
      out.write("               <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("                  class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a href=\"index.jsp\"><img src=\"images/C&C Logo.jpg\" alt=\"Logo\"\r\n");
      out.write("               width=\"120\" height=\"50\"></a>\r\n");
      out.write("            class=\"navbar-brand\"\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("               <li><a href=\"shortReservation.jsp\">단기렌트</a></li>\r\n");
      out.write("               class=\"active\"\r\n");
      out.write("               <li><a href=\"longReservation.jsp\">장기렌트</a></li>\r\n");
      out.write("               <li><a href=\"#\">P2P</a></li>\r\n");
      out.write("               <li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("               <li><a href=\"#\" role=\"button\" data-toggle=\"modal\"\r\n");
      out.write("                  data-target=\"#login-modal\"><span\r\n");
      out.write("                     class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("               <li><a href=\"#\" role=\"button\"><span\r\n");
      out.write("                     class=\"glyphicon glyphicon-log-in\"></span> 마이페이지</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </nav> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div class=\"container-fluid text-center\">\r\n");
      out.write("   <div class=\"row content\"> \r\n");
      out.write("      <div class=\"col-sm-2 sidenav\">\r\n");
      out.write("            <p>\r\n");
      out.write("               <a href=\"insuranceReservation.jsp\">보험약관</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("               <a href=\"noMemberReservation.jsp\">비회원 예약</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("               <a href=\"shortReservation.jsp\">단기 예약</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("               <a href=\"longReservation.jsp\">장기 예약</a>\r\n");
      out.write("            </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-8 text-left\">\r\n");
      out.write("         <h1>비회원 단기 예약</h1>\r\n");
      out.write("            <p>\r\n");
      out.write("            C&C렌터카는 국내 최대 규모의 네트워크로 한 걸음 더 앞서갑니다.<br>\r\n");
      out.write("            <br>\r\n");
      out.write("            전국 180여개 영업망과 55,000여대의 최신 차량 보유, 국내 최대 규모의 차량 선택 폭(수입차 및 LPG차량), 230여 정비네트워크의 편리한 사고, \r\n");
      out.write("            고장 처리 및 무상 대차 서비스 제공, 제주도 내 렌터카 1위, 최신 차량 2,000여대 보유, 다양한 파트너십을 통한 결합 상품 및 판매 채널 확대<br>\r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("            국내 최고의 선진화 된 렌터카 시스템으로 고객만족 서비스를 제공합니다.<br>\r\n");
      out.write("            \r\n");
      out.write("            Fresh Driving Campaign을 실시해 상쾌한 금연차량을 제공합니다.<br>\r\n");
      out.write("            더욱 빠르고 편리해진 Express 대여시스템(선결제 고객)으로 고객편의를 제공합니다. <br>\r\n");
      out.write("            홈페이지·모바일·컨택센터·제휴채널 등 언제 어디서나 편리한 예약시스템을 제공합니다.<br>\r\n");
      out.write("            차량관리시스템(FMS)을 통한 신속하고 투명한 장기렌탈서비스를 제공합니다.<br>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            C&C렌터카는 Total 자동차 서비스 전문브랜드입니다.<br>\r\n");
      out.write("            \r\n");
      out.write("            중고차 매입/판매/공매 및 차량정비 서비스 차량이동관련 물류사업,<br>\r\n");
      out.write("            주차장 운영, Maintenance Lease를 주력으로 하는 캐피탈 사업 운영자동차 Total 업체로서의 시너지 효과 창출<br>\r\n");
      out.write("            </p>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <h3>예약 하기</h3>            \r\n");
      out.write("            <section style=\"text-align:left\">\r\n");
      out.write("               <h3 align=\"center\">비회원 단기예약 하기</h3>\r\n");
      out.write("               \r\n");
      out.write("               <br>\r\n");
      out.write("               <!-- <form action=\"../../minsert\"> 상대경로 -->\r\n");
      out.write("               <form action=\"/cc/n_m_reservation\" method=\"post\"><!--절대경로  -->\r\n");
      out.write("               <table width=\"650\" align=\"center\">               \r\n");
      out.write("               <tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">*이 름</th>\r\n");
      out.write("                  <td><input type=\"text\" name=\"nomembername\" required></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">*식별번호</th>\r\n");
      out.write("                  <td><input type=\"text\" name=\"nomembernumber\" id=\"nomember1\" required></td>\r\n");
      out.write("               <tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">*식별번호확인</th>\r\n");
      out.write("                  <td><input type=\"text\" id=\"nomember2\" onblur=\"checkPwd();\"></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("                  <th width=\"150\">성 별 </th>\r\n");
      out.write("                  <td>\r\n");
      out.write("                  <input type=\"radio\" name=\"nomembergender\" value=\"M\">남 &nbsp;\r\n");
      out.write("                  <input type=\"radio\" name=\"nomembergender\" value=\"F\">여 \r\n");
      out.write("                  \r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">나 이</th>\r\n");
      out.write("                  <td><input type=\"number\" name=\"nomemberage\"min=\"20\"max=\"100\"></td>\r\n");
      out.write("               </tr><tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">이메일</th>\r\n");
      out.write("                  <td><input type=\"email\" name=\"nomemberemail\"></td>\r\n");
      out.write("               </tr><tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">전화번호</th>\r\n");
      out.write("                  <td><input type=\"tel\" name=\"nomembertell\"></td>\r\n");
      out.write("               </tr><tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">대여일자</th>\r\n");
      out.write("                  <td >\r\n");
      out.write("                     <p>\r\n");
      out.write("                        <input type=\"text\" name=\"carstartdate\" id=\"datepicker1\" />\r\n");
      out.write("                      </p>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">반납일자</th>\r\n");
      out.write("                  <td>\r\n");
      out.write("                      <p>\r\n");
      out.write("                        <input type=\"text\" name=\"carenddate\" id=\"datepicker2\" />\r\n");
      out.write("                      </p>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">차종선택</th>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <select  class=\"catype_select\" id =\"catype_select\" name=\"cartype_no\">\r\n");
      out.write("                        <option >차종</option>\r\n");
      out.write("                        <option value=\"1\">소형</option>\r\n");
      out.write("                        <option value=\"2\">중형</option>\r\n");
      out.write("                        <option value=\"3\">대형</option>\r\n");
      out.write("                     </select>\r\n");
      out.write("                     <select>\r\n");
      out.write("                        <option></option>\r\n");
      out.write("                     \r\n");
      out.write("                     </select>\r\n");
      out.write("                     <select name=\"cartype_no\">\r\n");
      out.write("                     \r\n");
      out.write("                        <option>차량선택</option>\r\n");
      out.write("                        <option>??</option>\r\n");
      out.write("                        <option>??</option>\r\n");
      out.write("                        <option>??</option>\r\n");
      out.write("                     </select>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               \r\n");
      out.write("               <tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">보험선택</th>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <select name=\"carinsurance_no\">\r\n");
      out.write("                        <option>비회원보험선택</option>\r\n");
      out.write("                        <option>????</option>\r\n");
      out.write("                        <option>????</option>\r\n");
      out.write("                        <option>선택안함</option>\r\n");
      out.write("                     </select>                     \r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               <tr height=\"40\">\r\n");
      out.write("                  <th width=\"150\">특이사항</th>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <textarea name=\"carnote\" rows=\"3\" cols=\"30\">\r\n");
      out.write("                     </textarea>   \r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr height=\"40\" align=\"right\">\r\n");
      out.write("                  <th width=\"150\" colspan=\"2\">\r\n");
      out.write("                     <input type=\"submit\" value=\"대여하기\"> &nbsp;\r\n");
      out.write("                     <input type=\"reset\" value=\"작성취소\"> &nbsp;                     \r\n");
      out.write("                  </th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               </table>\r\n");
      out.write("               \r\n");
      out.write("               </form>\r\n");
      out.write("            </section>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- <footer class=\"container-fluid text-center\">\r\n");
      out.write("      <p>\r\n");
      out.write("         상호명 : C&C 렌터카 대표자 : 홍길동 주소 : 서울시 강남구 역삼동 대표자 전화번호 : 02-1234-1234<br>\r\n");
      out.write("         여기엔 무엇을 써야 하는가?\r\n");
      out.write("      </p>\r\n");
      out.write("   </footer> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
