/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-04-12 01:39:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.businessMy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;
import review.model.vo.*;
import java.util.*;
import reply.model.vo.*;
import coupon.model.vo.*;

public final class business_005fmy_005fHG_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("reply.model.vo");
    _jspx_imports_packages.add("coupon.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_packages.add("review.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//페이지관리 수정하기눌렀을때

	//로그인 정보 가져오기
	Member loginMember = null;
	if (session.getAttribute("loginMember") instanceof Business) {
		loginMember = (Business) session.getAttribute("loginMember");
	} else { //로그인 아니라면 index로 강제 소환

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tlocation.href =\"/food/index.jsp\";\r\n");
      out.write("\t</script>\r\n");

	}
	//tab 정보 가져오기
	if (request.getAttribute("tab") != null) {

      out.write("\r\n");
      out.write("<script> \r\n");
      out.write("var tab = '");
      out.print(request.getAttribute("tab"));
      out.write("';\r\n");
      out.write("</script>\r\n");

	} else {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar tab = \"tab-1\";\r\n");
      out.write("</script>\r\n");

	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>푸딩 사업자</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<script src=\"/food/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/jquery.scrollzer.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/skel.min.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/util.js\"></script>\r\n");
      out.write("<script src=\"/food/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/left-menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/top-menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/foot.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/left-menu-tab.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/right-menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/modInfo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/review.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/replay.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/business-my.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/map.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tif (tab != null) {\r\n");
      out.write("\t\t\t$('.tab-content').removeClass('current');\r\n");
      out.write("\t\t\t$('.tabs li').removeClass('current');\r\n");
      out.write("\t\t\t$('.tabs li a').removeClass('active');\r\n");
      out.write("\t\t\t$('#' + tab).addClass(' current');\r\n");
      out.write("\t\t\t$('[data-tab=' + tab + '] a').addClass('active');\r\n");
      out.write("\t\t\tconsole.log('[data-tab=' + tab + ']');\r\n");
      out.write("\t\t\ttab = null;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$('.tabs li').click(function() {\r\n");
      out.write("\t\t\tvar tab_cl = $(this).attr('data-tab');\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('.tabs li').removeClass('current');\r\n");
      out.write("\t\t\t$('.tab-content').removeClass('current');\r\n");
      out.write("\t\t\t$(this).addClass('current');\r\n");
      out.write("\t\t\t$(\".\" + tab_cl).addClass('current');\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('#delCheck').change(function() {\r\n");
      out.write("\t\t\t//리뷰 전체선택 체크박스 선택\r\n");
      out.write("\t\t\tif ($('#delCheck').is(\":checked\") == true) {\r\n");
      out.write("\t\t\t\t$('[name=delCheck]').attr(\"checked\", true);\r\n");
      out.write("\t\t\t} else if ($('#delCheck').is(\":checked\") == false) {\r\n");
      out.write("\t\t\t\t$('[name=delCheck]').attr(\"checked\", false);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('#reply_all_check').change(function() {\r\n");
      out.write("\t\t\t//댓글 전체선택 체크박스 선택\r\n");
      out.write("\t\t\tif ($('#reply_all_check').is(\":checked\") == true) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('[name=reply_check]').attr(\"checked\", true);\r\n");
      out.write("\t\t\t} else if ($('#reply_add_check').is(\":checked\") == false) {\r\n");
      out.write("\t\t\t\t$('[name=reply_check]').attr(\"checked\", false);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar tabe = location.hash;\r\n");
      out.write("\t\t\tif(tabe =='#edit'){\r\n");
      out.write("\t\t\t\t$('a[href$='+tabe+']').trigger(\"click\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar vcodeCheck = 1;\r\n");
      out.write("\tvar opwCheck = 1;\r\n");
      out.write("\tvar cpwCheck = 1;\r\n");
      out.write("\tvar vcode = null;\r\n");
      out.write("\tfunction checkMail() {\r\n");
      out.write("\r\n");
      out.write("\t\tif ($('#email2').val() != null) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif ($('#codeinput').css('display') == 'block'\r\n");
      out.write("\t\t\t\t\t|| $('#numbersend').text() == '인증번호 재발송') {\r\n");
      out.write("\t\t\t\t$('#codeinput').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('#numbersend').text('인증번호 발송');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar email = $(\"#email2\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar exptext = /^[A-Za-z0-9_\\.\\-]+@[A-Za-zS0-9\\-]+\\.[A-Za-z0-9\\-]+/;\r\n");
      out.write("\t\t\tif ($('#email2').val() == \"\") {\r\n");
      out.write("\t\t\t\talert(\"입력하신 이메일이 없습니다.\");\r\n");
      out.write("\t\t\t} else if (exptext.test(email) == false) {\r\n");
      out.write("\t\t\t\tif ($('#codeinput').css('display') == 'block'\r\n");
      out.write("\t\t\t\t\t\t|| $('#numbersend').text() == '인증번호 재발송') {\r\n");
      out.write("\t\t\t\t\t$('#codeinput').css('display', 'none');\r\n");
      out.write("\t\t\t\t\t$('#numbersend').text('인증번호 발송');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//이메일 형식이 알파벳+숫자@알파벳+숫자.알파벳+숫자 형식이 아닐경우\t\t\t\r\n");
      out.write("\t\t\t\talert(\"이메일형식이 올바르지 않습니다.\");\r\n");
      out.write("\t\t\t\t$('#email2').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/food/checkmail\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tuserId : $('#ID').val(),\r\n");
      out.write("\t\t\t\t\t\temail : $('#email2').val()\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tif (data == 0) {\r\n");
      out.write("\t\t\t\t\t\t\tif ($('#codeinput').css('display') == 'block'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t|| $('#numbersend').text() == '인증번호 재발송') {\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#codeinput').css('display', 'none');\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#numbersend').text('인증번호 발송');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\talert(\"중복되는 이메일 입니다.\");\r\n");
      out.write("\t\t\t\t\t\t} else if (data == 1) {\r\n");
      out.write("\t\t\t\t\t\t\t$('#numbersend').text(\"인증번호 재발송\");\r\n");
      out.write("\t\t\t\t\t\t\t$('#codeinput').css('display', 'block');\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"/food/sendmail\",\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\temail : $('#email2').val()\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvcode = Number(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(vcode);\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"인증번호를 전송하였습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction vCodeCheck() {\r\n");
      out.write("\t\t//이메일 인증버튼 클릭하면 실행되는 함수\r\n");
      out.write("\t\t//이메일 인증번호와 서버의 인증번호를 비교하여\r\n");
      out.write("\t\t//맞으면 checkVCode=true\r\n");
      out.write("\t\t//틀리면 checkVCode=false\r\n");
      out.write("\r\n");
      out.write("\t\tif (vcode == $('#vCode').val()) {\r\n");
      out.write("\t\t\talert('인증완료');\r\n");
      out.write("\t\t\tvcodeCheck = 0;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert('인증번호를 확인해주세요~ ^~!');\r\n");
      out.write("\t\t\tvcodeCheck = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checkPwd() {\r\n");
      out.write("\t\t//비밀번호 확인\r\n");
      out.write("\t\tif ($('#newPassword').val() != $('#newPasswordRepeat').val()) {\r\n");
      out.write("\t\t\talert('암호와 암호확인 값이 일치하지 않습니다.\\n' + '다시 입력하십시오.');\r\n");
      out.write("\t\t\t$('#newPasswordRepeat').val(\"\");\r\n");
      out.write("\t\t\tcpwCheck = 1;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tcpwCheck = 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction checkPwd2() {\r\n");
      out.write("\t\t//비밀번호 확인\r\n");
      out.write("\t\tvar regExp = /[\\{\\}\\[\\]\\/?.,;:|\\)*~`!^\\-_+<>@#$%&\\\\\\=\\(\\'\\\"\\s]/gi;\r\n");
      out.write("\t\tif ($('#oldPassword').val() != null && $('#newPassword').val()) {\r\n");
      out.write("\t\t\tif ($('#oldPassword').val() == $('#newPassword').val()) {\r\n");
      out.write("\t\t\t\talert('현재 비밀번호와 새 비밀번호가 같습니다.\\n' + '새 비밀번호를 다시 입력하십시오.');\r\n");
      out.write("\t\t\t\t$('#newPassword').val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (regExp.test($('#newPassword').val())) {\r\n");
      out.write("\t\t\talert(\"특수문자를 쓰실수없습니다.\");\r\n");
      out.write("\t\t\tvar m = $('#newPassword').val().replace(regExp, \"\");\r\n");
      out.write("\t\t\t$('#newPassword').val(\"\");\r\n");
      out.write("\t\t\t$('#newPassword').focus();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction checkOldPwd() {\r\n");
      out.write("\t\t//현재 비밀번호 확인\r\n");
      out.write("\t\tif ($('#oldPassword').val() != null\r\n");
      out.write("\t\t\t\t&& $('#oldPassword').val().length > 0) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/food/checkbspwd.pwenc\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"userPwd\" : $('#oldPassword').val(),\r\n");
      out.write("\t\t\t\t\t\"userId\" : $('#ID').val()\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == 0) {\r\n");
      out.write("\t\t\t\t\t\talert('현재 비밀번호가 일치하지 않습니다.');\r\n");
      out.write("\t\t\t\t\t\t$('#oldPassword').val('');\r\n");
      out.write("\t\t\t\t\t\topwCheck = 1;\r\n");
      out.write("\t\t\t\t\t} else if (data == 1) {\r\n");
      out.write("\t\t\t\t\t\topwCheck = 0;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction bsmodify() {\r\n");
      out.write("\t\tif (opwCheck == 0) {\r\n");
      out.write("\t\t\tif (cpwCheck == 0 && vcodeCheck == 0) {\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/food/bupdate.pwenc\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tuserId : $('#ID').val(),\r\n");
      out.write("\t\t\t\t\t\tuserPwd : $('#newPasswordRepeat').val(),\r\n");
      out.write("\t\t\t\t\t\temail : $('#email2').val()\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t$('#newPassword').text(\"\");\r\n");
      out.write("\t\t\t\t\t\t$('#newPasswordRepeat').text(\"\");\r\n");
      out.write("\t\t\t\t\t\t$('#codeinput').css('display', 'none');\r\n");
      out.write("\t\t\t\t\t\t$('#numbersend').text('인증번호 발송');\r\n");
      out.write("\t\t\t\t\t\t$('#email2').text(\"\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"/food/index.jsp\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (cpwCheck == 0 && vcodeCheck != 0\r\n");
      out.write("\t\t\t\t\t&& $('#newPasswordRepeat').val() != \"\") {\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/food/bupdate.pwenc\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tuserId : $('#ID').val(),\r\n");
      out.write("\t\t\t\t\t\tuserPwd : $('#newPasswordRepeat').val(),\r\n");
      out.write("\t\t\t\t\t\temail : $('#email').val()\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t$('#newPassword').text(\"\");\r\n");
      out.write("\t\t\t\t\t\t$('#newPasswordRepeat').text(\"\");\r\n");
      out.write("\t\t\t\t\t\t$('#email2').text(\"\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"/food/index.jsp\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (cpwCheck != 0 && vcodeCheck == 0) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/food/bupdate.pwenc\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tuserId : $('#ID').val(),\r\n");
      out.write("\t\t\t\t\t\tuserPwd : $('#oldPassword').val(),\r\n");
      out.write("\t\t\t\t\t\temail : $('#email2').val()\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t$('#newPassword').text(\"\");\r\n");
      out.write("\t\t\t\t\t\t$('#newPasswordRepeat').text(\"\");\r\n");
      out.write("\t\t\t\t\t\t$('#codeinput').css('display', 'none');\r\n");
      out.write("\t\t\t\t\t\t$('#numbersend').text('인증번호 발송');\r\n");
      out.write("\t\t\t\t\t\t$('#email2').text(\"\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"/food/index.jsp\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"입력하신 정보가 없습니다.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"현재 비밀번호를 입력해주세요.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction withdraw() {\r\n");
      out.write("\t\tif (opwCheck == 0) {\r\n");
      out.write("\t\t\tvar answer = confirm(\"정말 탈퇴 하시겠습니까 ? \");\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (answer) {\r\n");
      out.write("\t\t\t\tvar writer = prompt(\"\\\"탈퇴\\\"라고 적어주세요.\");\r\n");
      out.write("\t\t\t\tif (writer == \"탈퇴\") {\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"/food/withdraw\",\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\tbId : $('#ID').val(),\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\tif (data == 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"현재 비밀번호를 입력해주세요.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#map_wrap:active {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#map:active {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("#dialog-background {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.5);\r\n");
      out.write("\tz-index: 10;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#my-dialog {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tleft: calc(50% - 160px);\r\n");
      out.write("\ttop: calc(50% - 70px);\r\n");
      out.write("\twidth: 320px;\r\n");
      out.write("\theight: 140px;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tz-index: 11;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"navcl\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"/food/index.jsp\">Logo</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/views/search/search_location.jsp\">지역검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/flist\">푸드트럭</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/views/festival/festival.jsp\">축제검색</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t");

						if (loginMember == null) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/views/logIn/logIn.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/views/signUp/select_signUp.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> 회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						} else if (loginMember instanceof Business) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t<li><a><span class=\"glyphicon glyphicon-log-in\"></span> ");
      out.print(((Business) loginMember).getBusiness_Id());
      out.write("님\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/food/views/businessMy/business_my.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span>내 정보 보기</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/memberlogout\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span>로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"header\" style=\"top: 50px\">\r\n");
      out.write("\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t<ul id=\"ul\" class=\"tabs\">\r\n");
      out.write("\t\t\t\t<li class=\"current\" data-tab=\"tab-1\"><a href=\"#edit\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon fa-edit\">회원정보수정</span></a></li>\r\n");
      out.write("\t\t\t\t<!--  <li data-tab=\"tab-2\"><a href=\"#view\"><span class=\"icon fa-user\">내후기보기</span></a></li>-->\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-3\"><a href=\"/food/bsreplylist\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon fa-user\">내댓글보기</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-4\"><a href=\"/food/bclist\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon fa-envelope\">쿠폰확인</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-5\"><a href=\"/food/busedlist\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon fa-envelope-o\">쿠폰사용내역</span></a></li>\r\n");
      out.write("\t\t\t\t<li data-tab=\"tab-6\"><a href=\"#page\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon fa-th\">페이지관리</span></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- 회원정보 수정 코드 부분~~~ -->\r\n");
      out.write("\t<div id=\"tab-1\" class=\"tab-content tab-1 \" style=\"margin-bottom: 0px\">\r\n");
      out.write("\t\t<div id=\"tab-1div\">\r\n");
      out.write("\t\t\t<!-- <form id=\"frm\" method=\"post\" action=\"/food/bupdate.pwenc\"> -->\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<h1>회원정보 수정</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"input-group\" align=\"center\">\r\n");
      out.write("\t\t\t\t<input id=\"ID\" type=\"text\" class=\"form-control\" name=\"ID\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"아이디\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(((Business) loginMember).getBusiness_Id());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input id=\"oldPassword\" type=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tname=\"oldPassword\" placeholder=\"현재 비밀번호\" style=\"margin-top: 10px;\"\r\n");
      out.write("\t\t\t\t\tonblur=\"checkOldPwd();\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input id=\"newPassword\" type=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tname=\"newPassword\" placeholder=\"새 비밀번호\" style=\"margin-top: 10px;\"\r\n");
      out.write("\t\t\t\t\tonblur=\"checkPwd2();\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input id=\"newPasswordRepeat\" type=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tname=\"newPasswordRepeat\" placeholder=\"새 비밀번호 확인\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-top: 10px;\" onblur=\"checkPwd();\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input id=\"email\" type=\"text\" class=\"form-control\" name=\"email\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Email\" style=\"margin-top: 10px;\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(((Business) loginMember).getBusiness_Email());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input id=\"email2\" type=\"email\" class=\"form-control\" name=\"email2\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"new Email\" style=\"margin-top: 10px;\" required>\r\n");
      out.write("\t\t\t\t<button id=\"numbersend\" class=\"btn btn-outline-primary\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-top: 10px;\" onclick=\"checkMail();\">인증번호 발송</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"codeinput\" class=\"input-group\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<input id=\"vCode\" type=\"text\" class=\"form-control\" name=\"vCode\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"인증번호 입력\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-outline-primary\" style=\"margin-top: 10px;\"\r\n");
      out.write("\t\t\t\t\tonclick=\"vCodeCheck();\">확인</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"input-group\" style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t<span><button class=\"btn btn-outline-primary\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-right: 200px\" onclick=\"bsmodify();\">수정하기</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-outline-primary\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"position: absolute; margin-left: -80px\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"withdraw();\">탈퇴하기</button> </span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br> <br> <br>\r\n");
      out.write("\t\t\t<!-- </form> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 내 후기보기 코드 부분~~~~~ -->\r\n");
      out.write("\t<!--  \r\n");
      out.write("\t\t<div id=\"tab-2\" class=\"tab-content tab-2\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h1>내후기 보기</h1>\r\n");
      out.write("\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width: 10%; min-width: 100px;\"><input type=\"checkbox\">전체선택</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class=\"alert-link\" href=\"\">제목1</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class=\"alert-link\" href=\"\">제목2</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class=\"alert-link\" href=\"\">제목3</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class=\"alert-link\" href=\"\">제목4</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class=\"alert-link\" href=\"\">제목5</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class=\"alert-link\" href=\"\">제목6</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class=\"alert-link\" href=\"\">제목7</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class=\"alert-link\" href=\"\">제목8</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class=\"alert-link\" href=\"\">제목9</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<hr style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left: 35%\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\"><</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"end-page-item\"><button type=\"button\" class=\"btn btn-outline-primary\">삭제</button></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br><br><br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t-->\r\n");
      out.write("\t<!-- 내 댓글보기 코드 부분~~~~ -->\r\n");
      out.write("\t<div id=\"tab-3\" class=\"tab-content tab-3\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1>내댓글 보기</h1>\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"bsreplydel\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width: 10%; min-width: 100px;\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"checkbox\" id=\"reply_all_check\">전체선택</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>&nbsp;</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							int listCount = 0;
							int startPage = 0;
							int endPage = 0;
							int maxPage = 0;
							int currentPage = 0;
							if (request.getAttribute("reply_list") != null) {
								ArrayList<Reply> replyList = (ArrayList<Reply>) request.getAttribute("reply_list");
								listCount = ((Integer) request.getAttribute("listCount")).intValue();
								startPage = ((Integer) request.getAttribute("startPage")).intValue();
								endPage = ((Integer) request.getAttribute("endPage")).intValue();
								maxPage = ((Integer) request.getAttribute("maxPage")).intValue();
								currentPage = ((Integer) request.getAttribute("currentPage")).intValue();

								for (Reply reply : replyList) {
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"reply_check\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(reply.getReply_No());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t");

								if (reply.getReview_No() != 0) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(reply.getReply_Content());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th><a href=\"?review_no=");
      out.print(reply.getReview_No());
      out.write("\">원문보기</a></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(reply.getReply_Date());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th>&emsp;&emsp;&emsp;</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>&emsp;&emsp;&emsp;</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>&emsp;&emsp;&emsp;</th>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

							}
							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"삭제하기\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<hr style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t");

					if (currentPage <= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨처음]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/bsreplylist?page\">[맨처음]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage - 10) < startPage && (currentPage - 10) >= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/bsreplylist?page=");
      out.print(startPage - 1);
      out.write("\">[prev]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[prev]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 현재 페이지가 포함된 그룹의 페이지 숫자 출력 -->\r\n");
      out.write("\t\t\t\t");

					for (int p = startPage; p <= endPage; p++) {
						if (p == currentPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<font color=\"red\" size=\"4\"><b>[");
      out.print(p);
      out.write("]\r\n");
      out.write("\t\t\t\t</b></font>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/bsreplylist?page=");
      out.print(p);
      out.write('"');
      out.write('>');
      out.print(p);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage + 10) > endPage && (currentPage + 10) <= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/bsreplylist?page=");
      out.print(endPage + 1);
      out.write("\">[next]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[next]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (currentPage >= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨끝]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/bsreplylist?page=");
      out.print(maxPage);
      out.write("\">[맨끝]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br> <br> <br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"tab-4\" class=\"tab-content tab-4\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<form action=\"/food/bsearchid\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><h1>쿠폰 확인</h1></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-top: 20px; position: absolute; right: 20%;\"><input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" name=\"bSearchcusId\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"아이디 검색\" style=\"width-min: 130px;\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-top: 30px; position: absolute; right: 16%;\"><input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\" class=\"btn btn-outline-primary;\" value=\"검색\">\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"width: 10%; min-width: 100px;\">아이디</th>\r\n");
      out.write("\t\t\t\t\t\t<th>쿠폰</th>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"width: 12%; min-width: 100px;\">사용기한</th>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"width: 8%\"></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody style=\"text-align: center; vertical-align: middle;\">\r\n");
      out.write("\t\t\t\t\t");

						listCount = 0;
						startPage = 0;
						endPage = 0;
						maxPage = 0;
						currentPage = 0;
						if (request.getAttribute("coupon_blist") != null) { //쿠폰리스트 요청이 널이 아니라면
							ArrayList<Coupon_bl> couponList = (ArrayList<Coupon_bl>) request.getAttribute("coupon_blist");
							//쿠폰리스트를 어레이리스트에 담고
							listCount = ((Integer) request.getAttribute("listCount")).intValue();
							startPage = ((Integer) request.getAttribute("startPage")).intValue();
							endPage = ((Integer) request.getAttribute("endPage")).intValue();
							maxPage = ((Integer) request.getAttribute("maxPage")).intValue();
							currentPage = ((Integer) request.getAttribute("currentPage")).intValue();

							for (Coupon_bl bc : couponList) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t");
if(bc.getCustomer_id() != ""){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<th id=\"cuid\">");
      out.print(bc.getCustomer_id());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<th><a href=\"#\">");
      out.print(bc.getCoupon_content());
      out.write("</a></th>\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(bc.getCoupon_date());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"float: right;\"><button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-outline-primary\">사용</button></th>\r\n");
      out.write("\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<th>&emsp;&emsp;&emsp;</th>\r\n");
      out.write("\t\t\t\t\t\t<th>&emsp;&emsp;&emsp;</th>\r\n");
      out.write("\t\t\t\t\t\t<th>&emsp;&emsp;&emsp;</th>\r\n");
      out.write("\t\t\t\t\t\t<th>&emsp;&emsp;&emsp;</th>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						}
						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<hr style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t");

					if (currentPage <= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨처음]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/bclist?currentPage=1\">[맨처음]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage - 10) < startPage && (currentPage - 10) >= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/bclist?currentPage=");
      out.print(startPage - 1);
      out.write("\">[prev]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[prev]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 현재 페이지가 포함된 그룹의 페이지 숫자 출력 -->\r\n");
      out.write("\t\t\t\t");

					for (int p = startPage; p <= endPage; p++) {
						if (p == currentPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<font color=\"red\" size=\"4\"><b>[");
      out.print(p);
      out.write("]\r\n");
      out.write("\t\t\t\t</b></font>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/bclist?currentPage=");
      out.print(p);
      out.write('"');
      out.write('>');
      out.print(p);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage + 10) > endPage && (currentPage + 10) <= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/bclist?currentPage=");
      out.print(endPage + 1);
      out.write("\">[next]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[next]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (currentPage >= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨끝]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/bclist?currentPage=");
      out.print(maxPage);
      out.write("\">[맨끝]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- tab-4 끝나는 div -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"tab-5\" class=\"tab-content tab-5\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1>쿠폰 사용 내역</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"width: 10%; min-width: 100px;\">아이디</th>\r\n");
      out.write("\t\t\t\t\t\t<th>쿠폰</th>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"width: 15%; min-width: 100px;\">사용날짜</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody style=\"text-align: center; vertical-align: middle;\">\r\n");
      out.write("\t\t\t\t\t");

						listCount = 0;
						startPage = 0;
						endPage = 0;
						maxPage = 0;
						currentPage = 0;
						if (request.getAttribute("coupon_bulist") != null) { //쿠폰리스트 요청이 널이 아니라면
							ArrayList<Coupon_bl> couponList = (ArrayList<Coupon_bl>) request.getAttribute("coupon_bulist");
							//쿠폰리스트를 어레이리스트에 담고
							listCount = ((Integer) request.getAttribute("listCount")).intValue();
							startPage = ((Integer) request.getAttribute("startPage")).intValue();
							endPage = ((Integer) request.getAttribute("endPage")).intValue();
							maxPage = ((Integer) request.getAttribute("maxPage")).intValue();
							currentPage = ((Integer) request.getAttribute("currentPage")).intValue();

							for (Coupon_bl bc : couponList) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t");
if(bc.getCustomer_id() != ""){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(bc.getCustomer_id());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<th><a href=\"#\">");
      out.print(bc.getCoupon_content());
      out.write("</a></th>\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(bc.getCoupon_date());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<th>&emsp;&emsp;&emsp;</th>\r\n");
      out.write("\t\t\t\t\t\t<th>&emsp;&emsp;&emsp;</th>\r\n");
      out.write("\t\t\t\t\t\t<th>&emsp;&emsp;&emsp;</th>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						}
						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<hr style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t");

					if (currentPage <= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨처음]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/busedlist?currentPage=1\">[맨처음]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage - 10) < startPage && (currentPage - 10) >= 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/busedlist?currentPage=");
      out.print(startPage - 1);
      out.write("\">[prev]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[prev]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 현재 페이지가 포함된 그룹의 페이지 숫자 출력 -->\r\n");
      out.write("\t\t\t\t");

					for (int p = startPage; p <= endPage; p++) {
						if (p == currentPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<font color=\"red\" size=\"4\"><b>[");
      out.print(p);
      out.write("]\r\n");
      out.write("\t\t\t\t</b></font>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/busedlist?currentPage=");
      out.print(p);
      out.write('"');
      out.write('>');
      out.print(p);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if ((currentPage + 10) > endPage && (currentPage + 10) <= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/busedlist?currentPage=");
      out.print(endPage + 1);
      out.write("\">[next]</a>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t[next]&nbsp;\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (currentPage >= maxPage) {
				
      out.write("\r\n");
      out.write("\t\t\t\t[맨끝]&nbsp;\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/food/busedlist?currentPage=");
      out.print(maxPage);
      out.write("\">[맨끝]</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br> <br> <br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- tab-5끝나는 div -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"tab-6\" class=\"tab-content tab-6\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t<h2>&emsp;페이지관리</h2>\r\n");
      out.write("\t\t<hr style=\"height: 1px; background: black; width: 850px; float: left\">\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\t\t<div class=\"pagemain\">\r\n");
      out.write("\t\t\t<strong>푸드트럭 이름 </strong>&emsp;&emsp;&emsp;&emsp; <input type=\"text\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 200px;\"><font\r\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">&emsp;한글, 영문, 숫자\r\n");
      out.write("\t\t\t\t혼용가능(한글기준 10글자)</font> <br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\t\t\t<br> <br> <strong>공지사항</strong>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<input onfocus=\"this.value=''\" type=\"text\" value=\"한줄 공지사항\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 300px; color: gray\"><font\r\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">&emsp;한글, 영문, 숫자\r\n");
      out.write("\t\t\t\t혼용가능(한글기준 20글자)</font> <br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\t\t\t<br> <br> <strong>영업 시간 </strong>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("\t\t\t<select>\r\n");
      out.write("\t\t\t\t");

					for (int i = 0; i < 24; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<option>");
      out.print(i);
      out.write("\r\n");
      out.write("\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</select>시 <select>\r\n");
      out.write("\t\t\t\t");

					for (int j = 0; j <= 59; j++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<option>");
      out.print(j);
      out.write("\r\n");
      out.write("\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</select>분&nbsp;~&nbsp; <select>\r\n");
      out.write("\t\t\t\t");

					for (int i = 0; i < 24; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<option>");
      out.print(i);
      out.write("\r\n");
      out.write("\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</select>시 <select>\r\n");
      out.write("\t\t\t\t");

					for (int j = 0; j <= 59; j++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<option>");
      out.print(j);
      out.write("\r\n");
      out.write("\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</select>분 까지&emsp;<font style=\"color: gray; font-size: 10pt\">시간 타입 -\r\n");
      out.write("\t\t\t\t24시</font> <br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<strong style=\"float: left;\">트럭 사진 </strong>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br> <br> <br> <br> <br> <br> <br>\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\t\t\t<br> <br> <strong>연락처</strong>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("\t\t\t<input onfocus=\"this.value=''\" type=\"text\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 200px; color: gray\" value=\"ex) 010-1234-4567\">&emsp;<font\r\n");
      out.write("\t\t\t\tstyle=\"color: gray; font-size: 10pt\">\" - \" 생략가능</font> <br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<strong style=\"float: left;\">메뉴 추가 </strong>&emsp;&emsp;&emsp;\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br> <br> <br> <br> <br> <br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\t\t\t<br> <br> <strong style=\"float: left;\">장사 위치 </strong>\r\n");
      out.write("\t\t\t<div class=\"map_wrap\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 700px; height: 400px; margin-left: 100px; position: relative; border: 1px solid black; background: gray; display: table\">\r\n");
      out.write("\t\t\t\t<div id=\"map\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 700px; height: 400px; position: relative; overflow: hidden;\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"menu_wrap\" class=\"bg_white\">\r\n");
      out.write("\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;위치 : <input type=\"text\" value=\"서울\" id=\"keyword\" size=\"15\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"mfind\" type=\"submit\"  onclick=\"searchPlaces();\">검색하기</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- <font id=\"mwait\" style=\"display:table-cell; text-align:center; vertical-align:middle;\">검색해주세요.</font> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=15e2354024ec8ffe859e608291415c04&libraries=services\"></script>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\tvar mapContainer = document.getElementById('map'), mapOption = {\r\n");
      out.write("\t\t\t\t\tcenter : new daum.maps.LatLng(37.566826, 126.9786567),\r\n");
      out.write("\t\t\t\t\tlevel : 6\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar map = new daum.maps.Map(mapContainer, mapOption);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar ps = new daum.maps.services.Places();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tfunction searchPlaces() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar keyword = document.getElementById('keyword').value;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (!keyword.replace(/^\\s+|\\s+$/g, '')) {\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tps.keywordSearch(keyword, placesSearchCB);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tfunction placesSearchCB(data, status, pagination) {\r\n");
      out.write("\t\t\t\t\tif (status === daum.maps.services.Status.OK) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar bounds = new daum.maps.LatLngBounds();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tfor (var i = 0; i < data.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\tbounds.extend(new daum.maps.LatLng(data[i].y,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata[i].x));\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tmap.setBounds(bounds);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar marker = new daum.maps.Marker({\r\n");
      out.write("\t\t\t\t\tposition : map.getCenter()\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tmarker.setMap(map);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tdaum.maps.event.addListener(map, 'click', function(mouseEvent) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar latlng = mouseEvent.latLng;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tmarker.setPosition(latlng);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar x = latlng.getLat();\r\n");
      out.write("\t\t\t\t\tvar y = latlng.getLng();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('xloc').value = x;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('yloc').value = y;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\t$('li[data-tab=tab-6]').click(function() {\r\n");
      out.write("\t\t\t\t\t\tmap.relayout();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<br> <br> <br> <br> <br>\r\n");
      out.write("\t\t\t<hr style=\"width: 850px; float: left\">\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"/food/businessmy\">\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center; width: 850px\">\r\n");
      out.write("\t\t\t\t\t<!--xloc = x좌표,  yloc = y좌표  (value속성안에 값이 들어가있음)-->\r\n");
      out.write("\t\t\t\t\t<input name=\"xloc\" id=\"xloc\" type=\"text\"> <input\r\n");
      out.write("\t\t\t\t\t\tname=\"yloc\" id=\"yloc\" type=\"text\"> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"수정하기\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"clickLatlng\"></div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<br> <br> <br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- tab-6끝나는 div -->\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div class=\"foot\" style=\"bottom: 0; position: absolute;\">FoodTruck\r\n");
      out.write("\t\t\t&nbsp;Copyright @ iei.or.kr &nbsp; All Rights Reserved.</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
