/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2018-04-20 01:27:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.logIn;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pwd_005fEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
 if(request.getAttribute("message") != null){ 
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t var message = '");
      out.print(request.getAttribute("message"));
      out.write("';\n");
      out.write("\t alert(message);\n");
      out.write("\tlocation.href=\"/food/views/logIn/logIn.jsp\";\n");
      out.write("\t </script>\n");
      out.write("\t\n");
request.removeAttribute("message");
}else{
      out.write('\n');
      out.write('\n');
} 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<title>푸딩 비밀번호 변경</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/top-menu.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/foot.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/location.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/food/resources/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("\tsrc=\"/food/resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\n");
      out.write("\t//var vcode = 0;\n");
      out.write("\t//var vcodeCheck=0;\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\tfunction checkPwd() {\n");
      out.write("\t\t//비밀번호 확인\n");
      out.write("\t\tif ($('#pwd1').val() != $('#pwd2').val() && $('#pwd1').val() != null) {\n");
      out.write("\t\t\talert('암호와 암호확인 값이 일치하지 않습니다.\\n' + '다시 입력하십시오.');\n");
      out.write("\t\t\t$('#pwd2').val(\"\");\n");
      out.write("\t\t}\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- 상단 네비게이션 바 -->\n");
      out.write("\t<div class=\"navcl\">\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\" style=\"padding-left: 0px;\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\" >\n");
      out.write("\t\t\t\t\t<li style=\"margin-right:10px;\"><a class=\"navbar-brand\" href=\"/food/index.jsp \">\n");
      out.write("\t\t\t\t\t\t<img src=\"/food/resources/images/LOGO_fooding.png\" style=\"width:65px; height:30px; \">\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t<li ><a href=\"/food/index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/slocation\">지역검색</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/flist\">푸드트럭</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/food/fes_show\">축제검색</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"/food/views/logIn/logIn.jsp\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/food/views/signUp/select_signUp.jsp\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-edit\"></span> 회원가입</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- 비밀번호 찾기  -->\n");
      out.write("\t<div class=\"container\" style=\"margin-top: 50px;\">\n");
      out.write("\t\t<h3 style=\"text-align: center;\">새 비밀번호 설정</h3>\n");
      out.write("\t\t<br> <br>\n");
      out.write("\t\t<center>\n");
      out.write("\t\t\t<form style=\"width: 700px\" action=\"/food/editpwd.pwenc\" method=\"post\">\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"userid\" value=\"");
      out.print(request.getParameter("userId"));
      out.write("\">\n");
      out.write("\t\t\t\t<!-- 패스워드 입력란 -->\n");
      out.write("\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t<span class=\"input-group-addon\"><i\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\"></i></span> <input\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 570px; height: 25px;\" type=\"password\" id=\"pwd1\"\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" name=\"password\" placeholder=\"새 비밀번호\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<!-- 패스워드 확인 입력란 -->\n");
      out.write("\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t<span class=\"input-group-addon\"><i\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\"></i></span> <input\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 570px; height: 25px;\" id=\"pwd2\" type=\"password\" name=\"userPwd\"\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\"  onblur=\"checkPwd();\" placeholder=\"새 비밀번호 확인\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<!-- 확인 버튼 -->\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"확인\">\n");
      out.write("\t\t\t\t<br> <br> <br> <br>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("\t</center>\n");
      out.write("\t<br>\n");
      out.write("\t<div class=\"foot\" style=\"bottom: 0; position: absolute;\">\n");
      out.write("\t\t<p>FoodTruck &nbsp;Copyright @ iei.or.kr &nbsp; All Rights\n");
      out.write("\t\t\tReserved.</p>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
